// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const createClient: typeof autoImports.createClient
  const CommsHqError: typeof autoImports.CommsHqError
  const readFormFields: typeof autoImports.readFormFields
  const bindForm: typeof autoImports.bindForm
  const bindForms: typeof autoImports.bindForms
}

export {}
