/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      description: string
      subject_type: string
      subject_id: number
      causer: string
      properties: string
      ip_address: string
      user_id: number
    }
    ad_inventory: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      format: "newsletter" | "web" | "podcast" | "recommendation"
      position: string
      rate: number
      currency: string
      capacity: number
      status: "active" | "paused" | "sold_out" | "archived"
      team_id: number
      publication_id: number
    }
    ad_placements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      slot_key: string
      rate: number
      impressions: number
      clicks: number
      status: "reserved" | "approved" | "delivered" | "cancelled"
      team_id: number
      advertiser_offer_id: number
      campaign_id: number
      publication_id: number
    }
    advertiser_offers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      creative: unknown
      budget: number
      currency: string
      starts_at: string
      ends_at: string
      status: "draft" | "offered" | "accepted" | "active" | "completed" | "cancelled"
      team_id: number
      sponsor_id: number
    }
    ai_generations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      purpose: "writing" | "segmentation" | "summary" | "optimization" | "recommendation"
      idempotency_key: string
      model: string
      prompt_hash: string
      provenance: unknown
      output: string
      input_tokens: number
      output_tokens: number
      cost: number
      status: "generating" | "draft" | "approved" | "rejected" | "published" | "failed"
      failure_reason: string
      approved_by: number
      approved_at: string
      team_id: number
      user_id: number
    }
    analytics_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      category: string
      path: string
      value: number
      currency: string
      properties: string
    }
    attribution_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: "visit" | "signup" | "conversion" | "purchase" | "renewal" | "churn"
      source: string
      medium: string
      campaign_key: string
      revenue: number
      currency: string
      dedupe_key: string
      occurred_at: string
      team_id: number
      contact_id: number
      commerce_event_id: number
      campaign_id: number
    }
    auction_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      lot_number: number
      title: string
      description: string
      image_url: string
      category: string
      donor_name: string
      fair_market_value: number
      starting_bid: number
      min_increment: number
      buy_now_price: number
      reserve_price: number
      status: "open" | "closed" | "sold" | "passed"
      closes_at: string
      extension_count: number
      auction_id: number
    }
    auctions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      event_id: number
      title: string
      description: string
      status: "draft" | "preview" | "open" | "closed" | "settled"
      currency: string
      goal_amount: number
      opens_at: string
      closes_at: string
      anti_snipe_minutes: number
      extend_on_bid_window_minutes: number
      max_extensions: number
    }
    audience_exports: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "pending" | "processing" | "completed" | "expired" | "failed"
      filters: unknown
      storage_key: string
      row_count: number
      expires_at: string
      completed_at: string
      team_id: number
      audience_id: number
    }
    audience_imports: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      filename: string
      storage_key: string
      status: "pending" | "validating" | "processing" | "completed" | "failed"
      mapping: unknown
      total_rows: number
      imported_rows: number
      rejected_rows: number
      error_report_key: string
      completed_at: string
      team_id: number
      audience_id: number
    }
    audience_memberships: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "active" | "pending" | "unsubscribed"
      joined_at: string
      left_at: string
      team_id: number
      audience_id: number
      contact_id: number
    }
    audience_tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      color: string
      team_id: number
    }
    audiences: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      channel: "all" | "email" | "sms"
      member_count: number
      team_id: number
    }
    audit_events: {
      // columns
      id: number
      uuid: string
      action: string
      subject_type: string
      subject_id: string
      metadata: unknown
      ip_address: string
      occurred_at: string
      team_id: number
      user_id: number
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      bio: string
      avatar: string
      user_id: number
    }
    automation_approvals: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      action: string
      payload: unknown
      status: "pending" | "approved" | "rejected" | "expired" | "cancelled"
      requested_by: number
      decided_by: number
      reason: string
      expires_at: string
      decided_at: string
      team_id: number
      automation_id: number
      automation_run_id: number
      automation_step_run_id: number
    }
    automation_dead_letters: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      node_id: string
      payload: unknown
      error_class: string
      error_message: string
      attempts: number
      status: "open" | "replaying" | "recovered" | "discarded"
      recovered_by: number
      recovered_at: string
      team_id: number
      automation_id: number
      automation_run_id: number
      automation_step_run_id: number
    }
    automation_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "queued" | "running" | "waiting" | "completed" | "failed" | "cancelled"
      current_node_id: string
      version: number
      subject_type: string
      subject_id: string
      context: unknown
      idempotency_key: string
      started_at: string
      finished_at: string
      error: string
      team_id: number
      automation_id: number
    }
    automation_step_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      node_id: string
      type: string
      status: "queued" | "running" | "waiting" | "completed" | "failed" | "dead_lettered" | "cancelled"
      attempt: number
      idempotency_key: string
      input: unknown
      output: unknown
      error: string
      available_at: string
      started_at: string
      completed_at: string
      team_id: number
      automation_run_id: number
    }
    automation_versions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: number
      graph: unknown
      checksum: string
      published_by: number
      published_at: string
      team_id: number
      automation_id: number
    }
    automations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      status: "draft" | "active" | "paused" | "archived"
      version: number
      trigger: unknown
      graph: unknown
      published_at: string
      team_id: number
    }
    bids: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      bidder_name: string
      bidder_email: string
      amount: number
      max_amount: number
      status: "leading" | "outbid" | "won" | "lost" | "invalid"
      placed_at: string
      auction_id: number
      auction_item_id: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      position: number
      card_limit: number
      color: string
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      icon: string
      color: string
      position: number
      archived: number
      team_id: number
    }
    campaign_experiments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: "subject" | "sender" | "content" | "send_time"
      allocation: unknown
      winning_metric: "open_rate" | "click_rate" | "conversion_rate" | "revenue"
      status: "draft" | "running" | "evaluating" | "completed" | "cancelled"
      winner_variant_id: number
      evaluate_at: string
      completed_at: string
      team_id: number
      campaign_id: number
    }
    campaign_recipients: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: "email" | "sms"
      address_hash: string
      status: "queued" | "sent" | "delivered" | "failed" | "suppressed" | "cancelled"
      idempotency_key: string
      snapshot: unknown
      scheduled_at: string
      team_id: number
      campaign_id: number
      contact_id: number
      campaign_variant_id: number
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: "queued" | "deferred" | "sending" | "sent" | "delivered" | "failed" | "undelivered" | "bounced" | "complained" | "suppressed" | "cancelled"
      channel: "email" | "sms" | "push"
      recipient: string
      idempotency_key: string
      provider_message_id: string
      error: string
      sent_at: string
      opened_at: string
      clicked_at: string
      delivered_at: string
      failed_at: string
      segments: number
      cost: number
      metadata: unknown
      team_id: number
      campaign_variant_id: number
    }
    campaign_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      subject: string
      content: unknown
      allocation: number
      sent_count: number
      open_count: number
      click_count: number
      conversion_count: number
      is_winner: number
      team_id: number
      campaign_id: number
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      type: "email" | "sms" | "push" | "social" | "multi-channel"
      status: "draft" | "scheduled" | "sending" | "sent" | "paused" | "cancelled" | "failed" | "active" | "completed" | "archived"
      subject: string
      template: string
      text: string
      content: unknown
      channel_settings: unknown
      segment_definition: unknown
      from_name: string
      from_address: string
      reply_to: string
      timezone: string
      recurrence: string
      experiment_metric: "open_rate" | "click_rate" | "conversion_rate"
      email_list_id: number
      scheduled_at: string
      sent_at: string
      audience_size: number
      sent_count: number
      open_rate: number
      click_rate: number
      conversion_rate: number
      budget: number
      spent: number
      currency: string
      start_date: string
      end_date: string
      team_id: number
    }
    card_assignees: {
      // columns
      card_id: number
      user_id: number
      assigned_by_user_id: number | null
      created_at: string | null
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: string
    }
    card_labels: {
      // columns
      card_id: number
      label_id: number
      created_at: string | null
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: number
      board_id: number
      title: string
      description: string
      position: number
      created_by_user_id: number
      due_date: string
      archived: number
      board_column_id: number
      user_id: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: number
      unit_price: number
      total_price: number
      tax_rate: number
      tax_amount: number
      discount_percentage: number
      discount_amount: number
      product_name: string
      product_sku: string
      product_image: string
      notes: string
      cart_id: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "active" | "abandoned" | "converted" | "expired"
      total_items: number
      subtotal: number
      tax_amount: number
      discount_amount: number
      total: number
      expires_at: string
      currency: string
      notes: string
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      slug: string
      image_url: string
      is_active: number
      parent_category_id: string
      display_order: number
    }
    categorizable_models: {
      // columns
      id: number
      category_id: number
      categorizable_id: number
      categorizable_type: string
      created_at: string
      updated_at: string | null
    }
    categorizables: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string | null
      is_active: number
      categorizable_id: number
      categorizable_type: string
    }
    ci_run_states: {
      // columns
      repo_full_name: string
      last_conclusion: string | null
      last_run_id: number | null
      last_seen_at: string | null
      last_notified_at: string | null
      updated_at: string | null
    }
    ci_runner_alert_states: {
      // columns
      org: string
      alerting: number
      last_alerted_at: string | null
      last_cleared_at: string | null
      updated_at: string | null
    }
    ci_runner_samples: {
      // columns
      id: number
      org: string
      running: number
      queued: number
      cap: number
      sampled_at: string
    }
    commentables: {
      // columns
      id: number
      title: string
      body: string
      status: string
      approved_at: number | null
      rejected_at: number | null
      commentables_id: number
      commentables_type: string
      user_id: number | null
      is_active: number | null
      created_at: string
      updated_at: string | null
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: string
      author_email: string
      content: string
      body: string
      post_title: string
      status: "pending" | "approved" | "spam" | "trash"
      ip_address: string
      user_agent: string
      is_approved: number
      post_id: number
      user_id: number
    }
    commerce_connections: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider: "stacks" | "shopify" | "woocommerce" | "stripe" | "csv" | "api"
      name: string
      external_account_id: string
      encrypted_credentials: string
      status: "pending" | "active" | "error" | "disabled"
      cursor: string
      last_synced_at: string
      team_id: number
    }
    commerce_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      external_id: string
      type: "product_viewed" | "cart_updated" | "checkout_started" | "order_created" | "order_paid" | "order_fulfilled" | "order_refunded" | "subscription_changed"
      amount: number
      currency: string
      payload: unknown
      occurred_at: string
      team_id: number
      commerce_connection_id: number
      contact_id: number
    }
    commissions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: "referral" | "recommendation" | "sponsorship" | "affiliate"
      gross_amount: number
      fee_basis_points: number
      fee_amount: number
      net_amount: number
      currency: string
      status: "pending" | "approved" | "payable" | "paid" | "reversed"
      payable_at: string
      paid_at: string
      team_id: number
      earning_id: number
      referral_id: number
      recommendation_id: number
    }
    communication_suppressions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: string
      channel: "email" | "sms" | "push"
      reason: "unsubscribe" | "bounce" | "complaint" | "carrier" | "manual" | "legal"
      source: string
      suppressed_at: string
      lifted_at: string
      team_id: number
    }
    consent_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: string
      channel: "email" | "sms" | "push"
      action: "requested" | "granted" | "revoked" | "confirmed" | "suppressed"
      purpose: string
      source: string
      jurisdiction: string
      policy_version: string
      idempotency_key: string
      proof: unknown
      ip_address: string
      occurred_at: string
      team_id: number
    }
    contact_field_values: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      value: unknown
      team_id: number
      contact_id: number
      custom_field_id: number
    }
    contact_identities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: "email" | "sms" | "push" | "external"
      value: string
      verified_at: string
      is_primary: number
      team_id: number
      contact_id: number
    }
    contact_merges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      source_contact_uuid: string
      snapshot: unknown
      merged_by_user_id: number
      team_id: number
      contact_id: number
    }
    contact_tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      source: string
      applied_by: number
      team_id: number
      contact_id: number
      audience_tag_id: number
    }
    contacts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      phone: string
      first_name: string
      last_name: string
      status: "active" | "pending" | "unsubscribed" | "suppressed" | "archived"
      source: string
      properties: unknown
      last_engaged_at: string
      team_id: number
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      description: string
      status: "Active" | "Scheduled" | "Expired"
      is_active: number
      discount_type: "fixed_amount" | "percentage"
      discount_value: number
      min_order_amount: number
      max_discount_amount: number
      free_product_id: string
      usage_limit: number
      usage_count: number
      start_date: string
      end_date: string
      product_id: number
    }
    courier_pings: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      latitude: number
      longitude: number
      heading: number
      speed: number
      accuracy: number
      recorded_at: string
      courier_id: number
      delivery_route_id: number
    }
    couriers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      phone: string
      vehicle_number: string
      license: string
      status: "active" | "on_delivery" | "on_break" | "offline"
      latitude: number
      longitude: number
      heading: number
      speed: number
      last_ping_at: string
      user_id: number
    }
    custom_fields: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      key: string
      type: "text" | "number" | "boolean" | "date" | "select" | "json"
      options: unknown
      team_id: number
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      total_spent: number
      last_order: string
      status: "Active" | "Inactive"
      avatar: string
      user_id: number
    }
    data_requests: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: "access" | "export" | "erasure" | "restriction" | "correction"
      status: "pending" | "verifying" | "processing" | "completed" | "rejected"
      jurisdiction: string
      requested_at: string
      completed_at: string
      proof: unknown
      team_id: number
      contact_id: number
    }
    data_retention_policies: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: "contacts" | "events" | "deliveries" | "analytics" | "audit" | "integrations"
      retention_days: number
      legal_hold: number
      jurisdiction: string
      status: "active" | "paused"
      team_id: number
    }
    dead_letter_jobs: {
      // columns
      id: number
      uuid: string
      connection: string
      queue: string
      payload: string
      exception: string
      reason: string
      total_failures: number
      first_failed_at: string | null
      last_failed_at: string | null
      dead_lettered_at: string
    }
    delivery_attempts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: "email" | "sms"
      provider: string
      provider_message_id: string
      idempotency_key: string
      attempt: number
      status: "pending" | "sending" | "deferred" | "sent" | "failed" | "dead_lettered"
      retry_class: "transient" | "rate_limited" | "permanent" | "suppressed"
      error_code: string
      error_message: string
      retry_at: string
      attempted_at: string
      team_id: number
      campaign_recipient_id: number
      campaign_send_id: number
    }
    delivery_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: "email" | "sms" | "push"
      type: "queued" | "sent" | "delivered" | "opened" | "clicked" | "failed" | "bounced" | "complained" | "unsubscribed"
      provider: string
      provider_event_id: string
      delivery_key: string
      payload: unknown
      occurred_at: string
      team_id: number
      contact_id: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      courier: string
      vehicle: string
      stops: number
      delivery_time: number
      total_distance: number
      last_active: number
      status: "planned" | "active" | "completed" | "cancelled"
      started_at: string
      completed_at: string
      courier_id: number
    }
    delivery_stops: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      sequence: number
      status: "pending" | "en_route" | "arrived" | "completed" | "failed" | "skipped"
      address: string
      latitude: number
      longitude: number
      recipient_name: string
      recipient_phone: string
      eta_at: string
      notified_nearby_at: string
      arrived_at: string
      completed_at: string
      notes: string
      type: "pickup" | "dropoff"
      delivery_route_id: number
      order_id: number
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commit_hash: string
      commit_message: string
      branch: string
      status: string
      environment: string
      duration: number
      author: string
      url: string
      error_log: string
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      download_limit: number
      expiry_days: number
      requires_login: number
      automatic_delivery: number
      status: "active" | "inactive"
    }
    earnings: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      source_type: "paid_publication" | "sponsorship" | "recommendation" | "digital_product" | "referral"
      source_id: string
      gross_amount: number
      fee_amount: number
      net_amount: number
      currency: string
      occurred_at: string
      team_id: number
      ad_placement_id: number
    }
    email_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      message_id: string
      recipient: string
      subject: string
      provider: string
      success: number
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      subscribed_at: string
      unsubscribed_at: string
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      subscriber_count: number
      active_count: number
      unsubscribed_count: number
      bounced_count: number
      status: "active" | "inactive" | "archived"
      is_public: number
      double_opt_in: number
    }
    email_messages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      subject: string
      preheader: string
      from_name: string
      from_address: string
      reply_to: string
      document: unknown
      html: string
      text: string
      revision: number
      team_id: number
      campaign_id: number
      message_template_id: number
      sender_identity_id: number
    }
    email_suppressions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: string
      type: "bounce" | "complaint" | "unsubscribe" | "manual"
      reason: string
    }
    email_webhook_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: "mailgun" | "postmark" | "ses" | "sendgrid"
      event_id: string
      processed_at: string
    }
    entitlements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      value: unknown
      source: "plan" | "override" | "promotion"
      expires_at: string
      team_id: number
      subscription_id: number
    }
    episodes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      summary: string
      audio_url: string
      duration_seconds: number
      published_at: string
      status: "draft" | "scheduled" | "published" | "archived"
      team_id: number
      podcast_id: number
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: string
      message: string
      stack: string
      status: number
      additional_info: string
    }
    failed_jobs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      connection: string
      queue: string
      payload: string
      exception: string
      attempts: number
      max_attempts: number
      duration_ms: number
      failed_at: string
    }
    form_definitions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      kind: "inline" | "popup" | "landing_page" | "gated_resource"
      schema_document: unknown
      double_opt_in: number
      status: "draft" | "active" | "archived"
      team_id: number
      site_id: number
      audience_id: number
    }
    form_fields: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: string
      label: string
      type: "text" | "textarea" | "email" | "phone" | "select" | "checkbox" | "radio" | "date" | "file" | "currency" | "section_break"
      required: number
      position: number
      width: "full" | "half"
      options: unknown
      conditions: unknown
      form_id: number
    }
    form_submissions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      payload: unknown
      dedupe_key: string
      source_url: string
      ip_hash: string
      status: "accepted" | "confirmed" | "rejected" | "spam"
      team_id: number
      form_definition_id: number
      contact_id: number
    }
    forms: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      handle: string
      status: "draft" | "active" | "closed"
      settings: unknown
      site_id: number
    }
    gated_resources: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      access: "subscriber" | "paid" | "product" | "segment"
      segment_id: number
      storage_key: string
      content: unknown
      status: "draft" | "published" | "archived"
      team_id: number
      publication_id: number
      product_id: number
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      initial_balance: number
      current_balance: number
      currency: string
      status: "ACTIVE" | "USED" | "EXPIRED" | "DEACTIVATED"
      purchaser_id: string
      recipient_email: string
      recipient_name: string
      personal_message: string
      is_digital: number
      is_reloadable: number
      is_active: number
      expiry_date: string
      last_used_date: string
      template_id: string
      customer_id: number
    }
    integration_credentials: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider: "twilio" | "stripe" | "shopify" | "woocommerce" | "mail" | "bedrock" | "yelp" | "google_business" | "generic"
      name: string
      encrypted_value: string
      last_four: string
      rotated_at: string
      team_id: number
    }
    job_batches: {
      // columns
      id: string
      name: string
      total_jobs: number
      pending_jobs: number
      failed_jobs: number
      failed_job_ids: string
      options: string | null
      cancelled_at: string | null
      created_at: string
      finished_at: string | null
      then_handler: string | null
      catch_handler: string | null
      finally_handler: string | null
    }
    job_idempotency: {
      // columns
      id: number
      idempotency_key: string
      job_name: string
      queue: string
      dispatched_at: string
    }
    job_quarantine: {
      // columns
      id: number
      job_name: string
      payload_hash: string
      failure_count: number
      window_start: string
      quarantined_at: string | null
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: string
      payload: string
      attempts: number
      available_at: number
      reserved_at: number
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: string
      color: string
    }
    landing_pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      status: "draft" | "scheduled" | "published" | "archived"
      document: unknown
      seo: unknown
      published_at: string
      team_id: number
      site_id: number
      publication_id: number
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: string
      template: "Standard License" | "Premium License" | "Enterprise License"
      expiry_date: string
      status: "active" | "inactive" | "unassigned"
      customer_id: number
      product_id: number
      order_id: number
    }
    link_pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      bio: string
      links: unknown
      theme: unknown
      status: "draft" | "published" | "archived"
      team_id: number
      site_id: number
      publication_id: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: number
      type: "warning" | "error" | "info" | "success"
      source: "file" | "cli" | "system"
      message: string
      project: string
      stacktrace: string
      file: string
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: string
      points: number
      source: string
      source_reference_id: string
      description: string
      expiry_date: string
      is_used: number
      customer_id: number
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      points_required: number
      reward_type: string
      discount_percentage: number
      free_product_id: string
      is_active: number
      expiry_days: number
      image_url: string
      product_id: number
    }
    magic_link_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: string
      token: string
      expires_at: string
      consumed_at: string
      redirect_to: string
      site_id: number
      user_id: number
    }
    mail_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      mailbox: string
      account_name: string
      signature: string
      display_density: "comfortable" | "default" | "compact"
      theme: "light" | "dark" | "system"
      language: "en" | "fr" | "de" | "es" | "ja"
      default_reply_behavior: "reply" | "replyAll"
      send_and_archive: number
      auto_advance: "newer" | "older" | "back"
      desktop_notifications: number
      notification_sound: "default" | "subtle" | "none"
      notification_preview: number
      filters: string
      blocked_senders: string
      labels: string
      load_remote_images: number
      show_external_content: number
      vacation_enabled: number
      vacation_start_date: string
      vacation_end_date: string
      vacation_subject: string
      vacation_message: string
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: string
      description: string
      country: string
      featured: number
    }
    menu_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      label: string
      url: string
      target: "_self" | "_blank"
      parent_id: number
      position: number
      visibility: "public" | "auth"
      menu_id: number
      page_id: number
    }
    menus: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      handle: string
      name: string
      site_id: number
    }
    message_blocks: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: "heading" | "text" | "image" | "button" | "divider" | "product" | "columns" | "footer"
      content: unknown
      styles: unknown
      position: number
      reusable: number
      team_id: number
      message_template_id: number
    }
    message_templates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      channel: "email" | "sms" | "landing_page"
      subject: string
      document: unknown
      plain_text: string
      revision: number
      team_id: number
    }
    monitored_profiles: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      platform: "google_business" | "yelp" | "facebook" | "instagram" | "x" | "tiktok" | "linkedin" | "youtube" | "trustpilot" | "reddit"
      kind: "business_listing" | "social_handle"
      display_name: string
      handle: string
      external_id: string
      location_label: string
      profile_url: string
      status: "active" | "paused" | "unconfigured" | "error"
      poll_interval_minutes: number
      next_poll_at: string
      last_polled_at: string
      last_mention_at: string
      cursor: string
      consecutive_failures: number
      last_error: string
      team_id: number
      integration_credential_id: number
    }
    notification_deliveries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      channel: "email" | "sms" | "chat" | "database" | "push" | "broadcast"
      recipient: string
      subject: string
      body: string
      status: "pending" | "sent" | "delivered" | "failed"
      error: string
      metadata: string
      sent_at: string
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      data: string
      read_at: string
      user_id: number
    }
    oauth_access_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      tokenable_type: string
      tokenable_id: number
      name: string
      token: string
      scopes: string
      revoked: number
      expires_at: string
      user_agent: string
      ip_address: string
    }
    order_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: string
      order_id: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: number
      price: number
      special_instructions: string
      order_id: number
      product_id: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: string
      total_amount: number
      currency: string
      tax_amount: number
      discount_amount: number
      delivery_fee: number
      tip_amount: number
      order_type: string
      delivery_address: string
      special_instructions: string
      estimated_delivery_time: string
      tracking_token: string
      delivery_latitude: number
      delivery_longitude: number
      applied_coupon_id: string
      customer_id: number
      coupon_id: number
    }
    page_revisions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      revision: number
      title: string
      blocks: unknown
      meta_description: string
      note: string
      page_id: number
      author_id: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      path: string
      parent_id: number
      template: string
      blocks: unknown
      meta_description: string
      status: "draft" | "published" | "scheduled" | "archived"
      scheduled_at: string
      views: number
      published_at: string
      conversions: number
      author_id: number
      site_id: number
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      last_four: number
      brand: string
      exp_month: number
      exp_year: number
      is_default: number
      provider_id: string
      user_id: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      key: string
      unit_price: number
      status: string
      image: string
      provider_id: string
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      amount: number
      type: string
      provider_id: string
      user_id: number
      payment_method_id: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      method: "cash" | "creditCard" | "debitCard" | "paypal" | "applePay" | "googlePay" | "bankTransfer" | "giftCard"
      status: "pending" | "processing" | "completed" | "failed" | "refunded" | "partiallyRefunded" | "succeeded"
      currency: string
      reference_number: string
      card_last_four: string
      card_brand: string
      billing_email: string
      transaction_id: string
      payment_provider: string
      refund_amount: number
      notes: string
      order_id: number
      customer_id: number
    }
    payouts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider_id: string
      amount: number
      currency: string
      status: "pending" | "processing" | "paid" | "failed" | "cancelled"
      scheduled_at: string
      paid_at: string
      team_id: number
    }
    permissions: {
      // columns
      id: number
      name: string
      guard_name: string
      description: string | null
      created_at: string | null
      updated_at: string | null
    }
    pledges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      donor_name: string
      donor_email: string
      amount: number
      level: string
      status: "pending" | "confirmed" | "cancelled"
      auction_id: number
      customer_id: number
    }
    podcasts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      description: string
      author: string
      explicit: number
      status: "draft" | "active" | "archived"
      team_id: number
      publication_id: number
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: string
      slug: string
      poster: string
      content: string
      excerpt: string
      focus_keyword: string
      meta_description: string
      canonical_url: string
      views: number
      published_at: string
      status: "published" | "draft" | "archived"
      is_featured: number
      author_id: number
      site_id: number
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      mac_address: string
      location: string
      terminal: string
      status: "online" | "offline" | "warning"
      last_ping: number
      print_count: number
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      abbreviation: string
      type: string
      description: string
      is_default: number
      product_id: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: string
      type: string
      description: string
      options: string
      status: "active" | "inactive" | "draft"
      product_id: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      price: number
      image_url: string
      is_available: number
      inventory_count: number
      preparation_time: number
      allergens: string
      nutritional_info: string
      category_id: number
      manufacturer_id: number
    }
    publication_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: "pending" | "active" | "cancelled" | "past_due"
      tier: string
      started_at: string
      ended_at: string
      team_id: number
      publication_id: number
      contact_id: number
    }
    publications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      status: "draft" | "active" | "paused" | "archived"
      access: "free" | "paid" | "mixed"
      settings: unknown
      team_id: number
      site_id: number
    }
    query_logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      query: string
      normalized_query: string
      duration: number
      connection: string
      status: "completed" | "failed" | "slow"
      error: string
      executed_at: string
      bindings: string
      trace: string
      model: string
      method: string
      file: string
      line: number
      memory_usage: number
      rows_affected: number
      transaction_id: string
      tags: string
      affected_tables: string
      indexes_used: string
      missing_indexes: string
      explain_plan: string
      optimization_suggestions: string
    }
    queue_circuit_state: {
      // columns
      queue_name: string
      success_count: number
      failure_count: number
      window_start: string
      paused_at: string | null
      resume_at: string | null
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: string
      document: string
      timestamp: string
      status: "success" | "failed" | "warning"
      size: number
      pages: number
      duration: number
      metadata: string
      print_device_id: number
    }
    recommendations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      partner_publication_id: number
      direction: "outbound" | "inbound" | "exchange"
      status: "pending" | "active" | "paused" | "declined" | "ended"
      reward_amount: number
      currency: string
      terms: unknown
      team_id: number
      publication_id: number
    }
    redirects: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      from_path: string
      to_path: string
      status_code: number
      source: "slug-change" | "manual"
      site_id: number
    }
    referral_codes: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: number
      code: string
    }
    referrals: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: string
      referred_email_hash: string
      status: "clicked" | "pending" | "qualified" | "rewarded" | "rejected"
      reward: unknown
      qualified_at: string
      team_id: number
      publication_id: number
      contact_id: number
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: string
      type: string
      status: string
      notes: string
      downloads: number
      author: string
    }
    reputation_alert_rules: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      metric: "negative_mention_count" | "mention_volume" | "average_rating" | "average_sentiment" | "unanswered_negative_count"
      comparator: "gte" | "lte"
      threshold: number
      window_minutes: number
      minimum_sample_size: number
      platforms: unknown
      severity: "info" | "warning" | "critical"
      channels: unknown
      cooldown_minutes: number
      status: "active" | "paused"
      next_evaluation_at: string
      last_evaluated_at: string
      last_triggered_at: string
      team_id: number
    }
    reputation_alerts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      fingerprint: string
      metric: "negative_mention_count" | "mention_volume" | "average_rating" | "average_sentiment" | "unanswered_negative_count"
      severity: "info" | "warning" | "critical"
      observed_value: number
      threshold_value: number
      sample_size: number
      window_start: string
      window_end: string
      status: "open" | "acknowledged" | "resolved"
      context: string
      notified_channels: unknown
      acknowledged_by: number
      acknowledged_at: string
      resolved_at: string
      team_id: number
      reputation_alert_rule_id: number
    }
    reputation_mentions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      platform: "google_business" | "yelp" | "facebook" | "instagram" | "x" | "tiktok" | "linkedin" | "youtube" | "trustpilot" | "reddit"
      kind: "review" | "comment" | "mention" | "question"
      external_id: string
      author_name: string
      author_handle: string
      body: string
      rating: number
      sentiment: "positive" | "neutral" | "negative" | "unknown"
      sentiment_score: number
      language: string
      url: string
      status: "new" | "triaged" | "responded" | "ignored"
      responded_at: string
      responded_by: number
      raw: string
      posted_at: string
      fetched_at: string
      team_id: number
      monitored_profile_id: number
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS" | "HEAD"
      path: string
      status_code: number
      duration_ms: number
      ip_address: string
      memory_usage: number
      user_agent: string
      error_message: string
    }
    reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rating: number
      title: string
      content: string
      is_verified_purchase: number
      is_approved: number
      is_featured: number
      helpful_votes: number
      unhelpful_votes: number
      purchase_date: string
      images: string
      product_id: number
      customer_id: number
    }
    role_permissions: {
      // columns
      role_id: number
      permission_id: number
      created_at: string | null
    }
    roles: {
      // columns
      id: number
      name: string
      guard_name: string
      description: string | null
      created_at: string | null
      updated_at: string | null
    }
    segment_rules: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      field: string
      operator: "equals" | "not_equals" | "contains" | "greater_than" | "less_than" | "before" | "after" | "exists" | "not_exists" | "in"
      value: unknown
      position: number
      team_id: number
      segment_id: number
    }
    segment_snapshots: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rule_checksum: string
      contact_ids: unknown
      contact_count: number
      source: "campaign" | "automation" | "export" | "preview"
      created_by: number
      team_id: number
      segment_id: number
    }
    segments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      match_type: "all" | "any"
      estimated_count: number
      refreshed_at: string
      team_id: number
    }
    sender_domains: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      domain: string
      status: "pending" | "verified" | "failed" | "disabled"
      selector: string
      dns_records: unknown
      verified_at: string
      last_checked_at: string
      team_id: number
    }
    sender_identities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: "email" | "sms"
      name: string
      address: string
      reply_to: string
      status: "pending" | "verified" | "disabled" | "failed"
      verification: unknown
      team_id: number
      sender_domain_id: number
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      base_rate: number
      free_shipping: number
      status: "active" | "inactive" | "draft"
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: number
      weight_to: number
      rate: number
      shipping_method_id: number
      shipping_zone_id: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      countries: string
      regions: string
      postal_codes: string
      status: "active" | "inactive" | "draft"
      shipping_method_id: number
    }
    site_domains: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      domain: string
      is_primary: number
      verified_at: string
      ssl_status: "pending" | "issued" | "failed"
      site_id: number
    }
    sites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      subdomain: string
      status: "active" | "suspended" | "archived"
      settings: unknown
      timezone: string
      team_id: number
    }
    sms_messages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      body: string
      encoding: "gsm7" | "ucs2"
      segment_count: number
      stop_language_included: number
      quiet_hours_timezone: string
      revision: number
      team_id: number
      campaign_id: number
      sender_identity_id: number
    }
    sms_opt_outs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      phone: string
      reason: string
      opted_out_at: string
    }
    social_accounts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: string
      provider_user_id: string
      provider_email: string
      user_id: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: string
      platform: "twitter" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube"
      status: "draft" | "scheduled" | "published" | "failed"
      scheduled_at: string
      published_at: string
      likes: number
      shares: number
      comments: number
      reach: number
      image_url: string
      external_id: string
      user_id: number
    }
    sponsors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      contact_email: string
      website: string
      status: "prospect" | "active" | "paused" | "blocked"
      notes: string
      team_id: number
    }
    storage_item_tasks: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      disk: string
      path: string
      kind: "optimize" | "transcode" | "tag"
      state: "queued" | "running" | "done" | "failed"
      attempts: number
      error: string
      started_at: string
      finished_at: string
    }
    storage_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      disk: string
      path: string
      favorite: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      source: string
      subscriber_id: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: string
      status: "subscribed" | "unsubscribed" | "pending" | "bounced"
      source: string
      unsubscribed_at: string
      user_id: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: string
      plan: string
      provider_id: string
      provider_status: string
      unit_price: number
      provider_type: string
      provider_price_id: string
      provider_customer_id: string
      quantity: number
      cancel_at_period_end: number
      trial_ends_at: string
      ends_at: string
      last_used_at: string
      team_id: number
      user_id: number
    }
    taggable_models: {
      // columns
      id: number
      tag_id: number
      taggable_id: number
      taggable_type: string
      created_at: string
      updated_at: string | null
    }
    taggables: {
      // columns
      id: number
      name: string
      slug: string
      description: string | null
      is_active: number
      taggable_id: number | null
      taggable_type: string
      created_at: string
      updated_at: string | null
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      slug: string
      description: string
      color: string
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      rate: number
      type: string
      country: string
      region: "North America" | "South America" | "Europe" | "Asia" | "Africa" | "Oceania" | "Antarctica"
      status: "active" | "inactive"
      is_default: number
      code: string
      exemptible: number
    }
    team_invitations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      email: string
      role: "admin" | "member" | "viewer"
      token_hash: string
      pending_key: string
      invited_by_user_id: number
      accepted_by_user_id: number
      status: "pending" | "accepted" | "revoked" | "expired"
      delivery_status: "pending" | "sent" | "failed"
      delivery_error: string
      expires_at: string
      delivered_at: string
      accepted_at: string
    }
    team_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      user_id: number
      role: "owner" | "admin" | "member" | "viewer"
      status: "active" | "suspended"
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      description: string
      member_count: number
      status: string
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: number
      status: string
      payment_method: string
      payment_details: string
      transaction_reference: string
      loyalty_points_earned: number
      loyalty_points_redeemed: number
      order_id: number
    }
    usage_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      meter: string
      quantity: number
      source_type: string
      source_id: string
      idempotency_key: string
      provider_cost: number
      metadata: unknown
      occurred_at: string
      team_id: number
      user_id: number
    }
    usage_meters: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: "contacts" | "emails" | "sms_segments" | "ai_generations" | "custom_domains"
      quantity: number
      included_quantity: number
      period_start: string
      period_end: string
      team_id: number
    }
    user_permissions: {
      // columns
      user_id: number
      permission_id: number
      created_at: string | null
    }
    user_roles: {
      // columns
      user_id: number
      role_id: number
      created_at: string | null
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_verified_at: string | null
      password_changed_at: string | null
      two_factor_secret: string | null
      two_factor_enabled: number | null
      two_factor_last_used_step: number | null
      stripe_id: string | null
      name: string
      email: string
      password: string
      avatar: string
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      quantity: number
      notification_preference: "sms" | "email" | "both"
      source: string
      notes: string
      status: "waiting" | "purchased" | "notified" | "cancelled"
      notified_at: string
      purchased_at: string
      cancelled_at: string
      product_id: number
      customer_id: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      email: string
      phone: string
      party_size: number
      check_in_time: string
      table_preference: "indoor" | "bar" | "booth" | "no_preference"
      status: "waiting" | "seated" | "cancelled" | "no_show"
      quoted_wait_time: number
      actual_wait_time: number
      queue_position: number
      seated_at: string
      no_show_at: string
      cancelled_at: string
      customer_id: number
    }
    webhook_endpoints: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: string
      provider: "twilio" | "stripe" | "shopify" | "woocommerce" | "mail" | "generic"
      direction: "inbound" | "outbound"
      url: string
      encrypted_secret: string
      events: unknown
      status: "active" | "paused" | "failing"
      team_id: number
    }
    webhook_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider: string
      provider_event_id: string
      type: string
      status: "received" | "processing" | "processed" | "failed" | "dead_lettered"
      payload: unknown
      signature_verified: number
      attempts: number
      error: string
      processed_at: string
      team_id: number
      webhook_endpoint_id: number
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: "disconnection" | "error" | "success"
      socket: string
      details: string
      time: number
    }
  }
}

export {}
