/* eslint-disable */
// AUTO-GENERATED by `buddy generate:db-types` — do not edit.
// Regenerate after adding/removing a model or changing its attributes.
// See stacksjs/stacks#1923.

declare module '@stacksjs/database' {
  interface DatabaseSchema {
    activities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      description: unknown
      subject_type: unknown
      subject_id: unknown
      causer: unknown
      properties: unknown
      ip_address: unknown
      user_id: number
    }
    ad_inventory: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      format: unknown
      position: unknown
      rate: unknown
      currency: unknown
      capacity: unknown
      status: unknown
      team_id: number
      publication_id: number
    }
    ad_placements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      slot_key: unknown
      rate: unknown
      impressions: unknown
      clicks: unknown
      status: unknown
      team_id: number
      advertiser_offer_id: number
      campaign_id: number
      publication_id: number
    }
    advertiser_offers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      creative: unknown
      budget: unknown
      currency: unknown
      starts_at: unknown
      ends_at: unknown
      status: unknown
      team_id: number
      sponsor_id: number
    }
    ai_generations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      purpose: unknown
      model: unknown
      prompt_hash: unknown
      provenance: unknown
      input_tokens: unknown
      output_tokens: unknown
      cost: unknown
      status: unknown
      approved_by: unknown
      approved_at: unknown
      team_id: number
      user_id: number
    }
    analytics_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      category: unknown
      path: unknown
      value: unknown
      currency: unknown
      properties: unknown
    }
    attribution_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: unknown
      source: unknown
      medium: unknown
      campaign_key: unknown
      revenue: unknown
      currency: unknown
      dedupe_key: unknown
      occurred_at: unknown
      team_id: number
      contact_id: number
      commerce_event_id: number
      campaign_id: number
    }
    auction_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      lot_number: unknown
      title: unknown
      description: unknown
      image_url: unknown
      category: unknown
      donor_name: unknown
      fair_market_value: unknown
      starting_bid: unknown
      min_increment: unknown
      buy_now_price: unknown
      reserve_price: unknown
      status: unknown
      closes_at: unknown
      extension_count: unknown
      auction_id: number
    }
    auctions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      event_id: unknown
      title: unknown
      description: unknown
      status: unknown
      currency: unknown
      goal_amount: unknown
      opens_at: unknown
      closes_at: unknown
      anti_snipe_minutes: unknown
      extend_on_bid_window_minutes: unknown
      max_extensions: unknown
    }
    audience_exports: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      filters: unknown
      storage_key: unknown
      row_count: unknown
      expires_at: unknown
      completed_at: unknown
      team_id: number
      audience_id: number
    }
    audience_imports: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      filename: unknown
      storage_key: unknown
      status: unknown
      mapping: unknown
      total_rows: unknown
      imported_rows: unknown
      rejected_rows: unknown
      error_report_key: unknown
      completed_at: unknown
      team_id: number
      audience_id: number
    }
    audience_memberships: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      joined_at: unknown
      left_at: unknown
      team_id: number
      audience_id: number
      contact_id: number
    }
    audience_tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      color: unknown
      team_id: number
    }
    audiences: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      channel: unknown
      member_count: unknown
      team_id: number
    }
    audit_events: {
      // columns
      id: number
      uuid: string
      action: unknown
      subject_type: unknown
      subject_id: unknown
      metadata: unknown
      ip_address: unknown
      occurred_at: unknown
      team_id: number
      user_id: number
    }
    authors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      bio: unknown
      avatar: unknown
      user_id: number
    }
    automation_approvals: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      action: unknown
      payload: unknown
      status: unknown
      requested_by: unknown
      decided_by: unknown
      reason: unknown
      expires_at: unknown
      decided_at: unknown
      team_id: number
      automation_id: number
      automation_run_id: number
      automation_step_run_id: number
    }
    automation_dead_letters: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      node_id: unknown
      payload: unknown
      error_class: unknown
      error_message: unknown
      attempts: unknown
      status: unknown
      recovered_by: unknown
      recovered_at: unknown
      team_id: number
      automation_id: number
      automation_run_id: number
      automation_step_run_id: number
    }
    automation_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      current_node_id: unknown
      version: unknown
      subject_type: unknown
      subject_id: unknown
      context: unknown
      idempotency_key: unknown
      started_at: unknown
      finished_at: unknown
      error: unknown
      team_id: number
      automation_id: number
    }
    automation_step_runs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      node_id: unknown
      type: unknown
      status: unknown
      attempt: unknown
      idempotency_key: unknown
      input: unknown
      output: unknown
      error: unknown
      available_at: unknown
      started_at: unknown
      completed_at: unknown
      team_id: number
      automation_run_id: number
    }
    automation_versions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: unknown
      graph: unknown
      checksum: unknown
      published_by: unknown
      published_at: unknown
      team_id: number
      automation_id: number
    }
    automations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      status: unknown
      version: unknown
      trigger: unknown
      graph: unknown
      published_at: unknown
      team_id: number
    }
    bids: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      bidder_name: unknown
      bidder_email: unknown
      amount: unknown
      max_amount: unknown
      status: unknown
      placed_at: unknown
      auction_id: number
      auction_item_id: number
    }
    board_columns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: unknown
      position: unknown
      card_limit: unknown
      color: unknown
    }
    boards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      icon: unknown
      color: unknown
      position: unknown
      archived: unknown
    }
    campaign_experiments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: unknown
      allocation: unknown
      winning_metric: unknown
      status: unknown
      winner_variant_id: unknown
      evaluate_at: unknown
      completed_at: unknown
      team_id: number
      campaign_id: number
    }
    campaign_recipients: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: unknown
      address_hash: unknown
      status: unknown
      idempotency_key: unknown
      snapshot: unknown
      scheduled_at: unknown
      team_id: number
      campaign_id: number
      contact_id: number
      campaign_variant_id: number
    }
    campaign_sends: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      campaign_id: number
      subscriber_id: number
      email_list_id: number
      status: unknown
      channel: unknown
      recipient: unknown
      idempotency_key: unknown
      provider_message_id: unknown
      error: unknown
      sent_at: unknown
      opened_at: unknown
      clicked_at: unknown
      delivered_at: unknown
      failed_at: unknown
      segments: unknown
      cost: unknown
      metadata: unknown
      team_id: number
      campaign_variant_id: number
    }
    campaign_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      subject: unknown
      content: unknown
      allocation: unknown
      sent_count: unknown
      open_count: unknown
      click_count: unknown
      conversion_count: unknown
      is_winner: unknown
      team_id: number
      campaign_id: number
    }
    campaigns: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      type: unknown
      status: unknown
      subject: unknown
      template: unknown
      text: unknown
      content: unknown
      channel_settings: unknown
      segment_definition: unknown
      from_name: unknown
      from_address: unknown
      reply_to: unknown
      timezone: unknown
      recurrence: unknown
      experiment_metric: unknown
      email_list_id: number
      scheduled_at: unknown
      sent_at: unknown
      audience_size: unknown
      sent_count: unknown
      open_rate: unknown
      click_rate: unknown
      conversion_rate: unknown
      budget: unknown
      spent: unknown
      currency: unknown
      start_date: unknown
      end_date: unknown
      team_id: number
    }
    card_comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      card_id: number
      user_id: number
      body: unknown
    }
    cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      column_id: unknown
      board_id: number
      title: unknown
      description: unknown
      position: unknown
      created_by_user_id: unknown
      due_date: unknown
      archived: unknown
      board_column_id: number
      user_id: number
    }
    cart_items: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      quantity: unknown
      unit_price: unknown
      total_price: unknown
      tax_rate: unknown
      tax_amount: unknown
      discount_percentage: unknown
      discount_amount: unknown
      product_name: unknown
      product_sku: unknown
      product_image: unknown
      notes: unknown
      cart_id: number
    }
    carts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      total_items: unknown
      subtotal: unknown
      tax_amount: unknown
      discount_amount: unknown
      total: unknown
      expires_at: unknown
      currency: unknown
      notes: unknown
      applied_coupon_id: unknown
      customer_id: number
      coupon_id: number
    }
    categories: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      slug: unknown
      image_url: unknown
      is_active: unknown
      parent_category_id: unknown
      display_order: unknown
    }
    categorizable_models: {
      // columns
      id: number
      category_id: number
      categorizable_id: number
      categorizable_type: string
      created_at: string
      updated_at: string | null
    }
    comments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      author_name: unknown
      author_email: unknown
      content: unknown
      body: unknown
      post_title: unknown
      status: unknown
      ip_address: unknown
      user_agent: unknown
      is_approved: unknown
      post_id: number
      user_id: number
    }
    commerce_connections: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider: unknown
      name: unknown
      external_account_id: unknown
      encrypted_credentials: unknown
      status: unknown
      cursor: unknown
      last_synced_at: unknown
      team_id: number
    }
    commerce_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      external_id: unknown
      type: unknown
      amount: unknown
      currency: unknown
      payload: unknown
      occurred_at: unknown
      team_id: number
      commerce_connection_id: number
      contact_id: number
    }
    commissions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: unknown
      gross_amount: unknown
      fee_basis_points: unknown
      fee_amount: unknown
      net_amount: unknown
      currency: unknown
      status: unknown
      payable_at: unknown
      paid_at: unknown
      team_id: number
      earning_id: number
      referral_id: number
      recommendation_id: number
    }
    communication_suppressions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: unknown
      channel: unknown
      reason: unknown
      source: unknown
      suppressed_at: unknown
      lifted_at: unknown
      team_id: number
    }
    consent_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      recipient: unknown
      channel: unknown
      action: unknown
      purpose: unknown
      source: unknown
      jurisdiction: unknown
      policy_version: unknown
      proof: unknown
      ip_address: unknown
      occurred_at: unknown
      team_id: number
    }
    contact_field_values: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      value: unknown
      team_id: number
      contact_id: number
      custom_field_id: number
    }
    contact_identities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: unknown
      value: unknown
      verified_at: unknown
      is_primary: unknown
      team_id: number
      contact_id: number
    }
    contact_merges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      source_contact_uuid: unknown
      snapshot: unknown
      merged_by_user_id: unknown
      team_id: number
      contact_id: number
    }
    contact_tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      source: unknown
      applied_by: unknown
      team_id: number
      contact_id: number
      audience_tag_id: number
    }
    contacts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: unknown
      phone: unknown
      first_name: unknown
      last_name: unknown
      status: unknown
      source: unknown
      properties: unknown
      last_engaged_at: unknown
      team_id: number
    }
    coupons: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: unknown
      description: unknown
      status: unknown
      is_active: unknown
      discount_type: unknown
      discount_value: unknown
      min_order_amount: unknown
      max_discount_amount: unknown
      free_product_id: unknown
      usage_limit: unknown
      usage_count: unknown
      start_date: unknown
      end_date: unknown
      product_id: number
    }
    custom_fields: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      key: unknown
      type: unknown
      options: unknown
      team_id: number
    }
    customers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      phone: unknown
      total_spent: unknown
      last_order: unknown
      status: unknown
      avatar: unknown
      user_id: number
    }
    data_requests: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      status: unknown
      jurisdiction: unknown
      requested_at: unknown
      completed_at: unknown
      proof: unknown
      team_id: number
      contact_id: number
    }
    data_retention_policies: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      kind: unknown
      retention_days: unknown
      legal_hold: unknown
      jurisdiction: unknown
      status: unknown
      team_id: number
    }
    delivery_attempts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: unknown
      provider: unknown
      provider_message_id: unknown
      idempotency_key: unknown
      attempt: unknown
      status: unknown
      retry_class: unknown
      error_code: unknown
      error_message: unknown
      retry_at: unknown
      attempted_at: unknown
      team_id: number
      campaign_recipient_id: number
      campaign_send_id: number
    }
    delivery_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: unknown
      type: unknown
      provider: unknown
      provider_event_id: unknown
      delivery_key: unknown
      payload: unknown
      occurred_at: unknown
      team_id: number
      contact_id: number
    }
    delivery_routes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      driver: unknown
      vehicle: unknown
      stops: unknown
      delivery_time: unknown
      total_distance: unknown
      last_active: unknown
      status: unknown
      started_at: unknown
      completed_at: unknown
      driver_id: number
    }
    delivery_stops: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      sequence: unknown
      status: unknown
      address: unknown
      latitude: unknown
      longitude: unknown
      recipient_name: unknown
      recipient_phone: unknown
      eta_at: unknown
      notified_nearby_at: unknown
      arrived_at: unknown
      completed_at: unknown
      notes: unknown
      delivery_route_id: number
      order_id: number
    }
    deployments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      commit_hash: unknown
      commit_message: unknown
      branch: unknown
      status: unknown
      environment: unknown
      duration: unknown
      author: unknown
      url: unknown
      error_log: unknown
    }
    digital_deliveries: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      download_limit: unknown
      expiry_days: unknown
      requires_login: unknown
      automatic_delivery: unknown
      status: unknown
    }
    driver_pings: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      latitude: unknown
      longitude: unknown
      heading: unknown
      speed: unknown
      accuracy: unknown
      recorded_at: unknown
      driver_id: number
      delivery_route_id: number
    }
    drivers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      phone: unknown
      vehicle_number: unknown
      license: unknown
      status: unknown
      latitude: unknown
      longitude: unknown
      heading: unknown
      speed: unknown
      last_ping_at: unknown
      user_id: number
    }
    earnings: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      source_type: unknown
      source_id: unknown
      gross_amount: unknown
      fee_amount: unknown
      net_amount: unknown
      currency: unknown
      occurred_at: unknown
      team_id: number
      ad_placement_id: number
    }
    email_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: unknown
      message_id: unknown
      recipient: unknown
      subject: unknown
      provider: unknown
      success: unknown
    }
    email_list_subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email_list_id: number
      subscriber_id: number
      status: unknown
      source: unknown
      subscribed_at: unknown
      unsubscribed_at: unknown
    }
    email_lists: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      description: unknown
      subscriber_count: unknown
      active_count: unknown
      unsubscribed_count: unknown
      bounced_count: unknown
      status: unknown
      is_public: unknown
      double_opt_in: unknown
    }
    email_messages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      subject: unknown
      preheader: unknown
      from_name: unknown
      from_address: unknown
      reply_to: unknown
      document: unknown
      html: unknown
      text: unknown
      revision: unknown
      team_id: number
      campaign_id: number
      message_template_id: number
      sender_identity_id: number
    }
    email_suppressions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: unknown
      type: unknown
      reason: unknown
    }
    email_webhook_events: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: unknown
      event_id: unknown
      processed_at: unknown
    }
    entitlements: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: unknown
      value: unknown
      source: unknown
      expires_at: unknown
      team_id: number
      subscription_id: number
    }
    episodes: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      slug: unknown
      summary: unknown
      audio_url: unknown
      duration_seconds: unknown
      published_at: unknown
      status: unknown
      team_id: number
      podcast_id: number
    }
    errors: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: unknown
      message: unknown
      stack: unknown
      status: unknown
      additional_info: unknown
    }
    failed_jobs: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      connection: unknown
      queue: unknown
      payload: unknown
      exception: unknown
      attempts: unknown
      max_attempts: unknown
      duration_ms: unknown
      failed_at: unknown
    }
    form_definitions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      kind: unknown
      schema_document: unknown
      double_opt_in: unknown
      status: unknown
      team_id: number
      site_id: number
      audience_id: number
    }
    form_fields: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      name: unknown
      label: unknown
      type: unknown
      required: unknown
      position: unknown
      width: unknown
      options: unknown
      conditions: unknown
      form_id: number
    }
    form_submissions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      payload: unknown
      dedupe_key: unknown
      source_url: unknown
      ip_hash: unknown
      status: unknown
      team_id: number
      form_definition_id: number
      contact_id: number
    }
    forms: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      handle: unknown
      status: unknown
      settings: unknown
      site_id: number
    }
    gated_resources: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      access: unknown
      segment_id: unknown
      storage_key: unknown
      content: unknown
      status: unknown
      team_id: number
      publication_id: number
      product_id: number
    }
    gift_cards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: unknown
      initial_balance: unknown
      current_balance: unknown
      currency: unknown
      status: unknown
      purchaser_id: unknown
      recipient_email: unknown
      recipient_name: unknown
      personal_message: unknown
      is_digital: unknown
      is_reloadable: unknown
      is_active: unknown
      expiry_date: unknown
      last_used_date: unknown
      template_id: unknown
      customer_id: number
    }
    integration_credentials: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider: unknown
      name: unknown
      encrypted_value: unknown
      last_four: unknown
      rotated_at: unknown
      team_id: number
    }
    jobs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      queue: unknown
      payload: unknown
      attempts: unknown
      available_at: unknown
      reserved_at: unknown
    }
    labels: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      board_id: number
      name: unknown
      color: unknown
    }
    landing_pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      status: unknown
      document: unknown
      seo: unknown
      published_at: unknown
      team_id: number
      site_id: number
      publication_id: number
    }
    license_keys: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: unknown
      template: unknown
      expiry_date: unknown
      status: unknown
      customer_id: number
      product_id: number
      order_id: number
    }
    link_pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      slug: unknown
      bio: unknown
      links: unknown
      theme: unknown
      status: unknown
      team_id: number
      site_id: number
      publication_id: number
    }
    logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      timestamp: unknown
      type: unknown
      source: unknown
      message: unknown
      project: unknown
      stacktrace: unknown
      file: unknown
    }
    loyalty_points: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      wallet_id: unknown
      points: unknown
      source: unknown
      source_reference_id: unknown
      description: unknown
      expiry_date: unknown
      is_used: unknown
    }
    loyalty_rewards: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      points_required: unknown
      reward_type: unknown
      discount_percentage: unknown
      free_product_id: unknown
      is_active: unknown
      expiry_days: unknown
      image_url: unknown
      product_id: number
    }
    magic_link_tokens: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      email: unknown
      token: unknown
      expires_at: unknown
      consumed_at: unknown
      redirect_to: unknown
      site_id: unknown
      user_id: number
    }
    mail_preferences: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      mailbox: unknown
      account_name: unknown
      signature: unknown
      display_density: unknown
      theme: unknown
      language: unknown
      default_reply_behavior: unknown
      send_and_archive: unknown
      auto_advance: unknown
      desktop_notifications: unknown
      notification_sound: unknown
      notification_preview: unknown
      filters: unknown
      blocked_senders: unknown
      labels: unknown
      load_remote_images: unknown
      show_external_content: unknown
      vacation_enabled: unknown
      vacation_start_date: unknown
      vacation_end_date: unknown
      vacation_subject: unknown
      vacation_message: unknown
    }
    manufacturers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      manufacturer: unknown
      description: unknown
      country: unknown
      featured: unknown
    }
    menu_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      label: unknown
      url: unknown
      target: unknown
      parent_id: unknown
      position: unknown
      visibility: unknown
      menu_id: number
      page_id: number
    }
    menus: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      handle: unknown
      name: unknown
      site_id: number
    }
    message_blocks: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      content: unknown
      styles: unknown
      position: unknown
      reusable: unknown
      team_id: number
      message_template_id: number
    }
    message_templates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      channel: unknown
      subject: unknown
      document: unknown
      plain_text: unknown
      revision: unknown
      team_id: number
    }
    notification_deliveries: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      user_id: unknown
      channel: string
      recipient: unknown
      subject: unknown
      body: unknown
      status: string
      error: unknown
      metadata: string
      sent_at: unknown
    }
    notifications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      data: string
      read_at: unknown
      user_id: number
    }
    order_idempotency: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      idempotency_key: unknown
      order_id: number
    }
    order_items: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      quantity: unknown
      price: unknown
      special_instructions: unknown
      order_id: number
      product_id: number
    }
    orders: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      total_amount: unknown
      currency: unknown
      tax_amount: unknown
      discount_amount: unknown
      delivery_fee: unknown
      tip_amount: unknown
      order_type: unknown
      delivery_address: unknown
      special_instructions: unknown
      estimated_delivery_time: unknown
      tracking_token: unknown
      delivery_latitude: unknown
      delivery_longitude: unknown
      applied_coupon_id: unknown
      customer_id: number
      coupon_id: number
    }
    page_revisions: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      revision: unknown
      title: unknown
      blocks: unknown
      meta_description: unknown
      note: unknown
      page_id: number
      author_id: number
    }
    pages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      slug: unknown
      path: unknown
      parent_id: unknown
      template: unknown
      blocks: unknown
      meta_description: unknown
      status: unknown
      scheduled_at: unknown
      views: unknown
      published_at: unknown
      conversions: unknown
      author_id: number
      site_id: number
    }
    payment_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      last_four: unknown
      brand: unknown
      exp_month: unknown
      exp_year: unknown
      is_default: unknown
      provider_id: unknown
      user_id: number
    }
    payment_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      key: unknown
      unit_price: unknown
      status: unknown
      image: unknown
      provider_id: unknown
    }
    payment_transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      amount: unknown
      type: unknown
      provider_id: unknown
      user_id: number
      payment_method_id: number
    }
    payments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: unknown
      method: unknown
      status: unknown
      currency: unknown
      reference_number: unknown
      card_last_four: unknown
      card_brand: unknown
      billing_email: unknown
      transaction_id: unknown
      payment_provider: unknown
      refund_amount: unknown
      notes: unknown
      order_id: number
      customer_id: number
    }
    payouts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider_id: unknown
      amount: unknown
      currency: unknown
      status: unknown
      scheduled_at: unknown
      paid_at: unknown
      team_id: number
    }
    pledges: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      donor_name: unknown
      donor_email: unknown
      amount: unknown
      level: unknown
      status: unknown
      auction_id: number
    }
    podcasts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      slug: unknown
      description: unknown
      author: unknown
      explicit: unknown
      status: unknown
      team_id: number
      publication_id: number
    }
    posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      title: unknown
      slug: unknown
      poster: unknown
      content: unknown
      excerpt: unknown
      focus_keyword: unknown
      meta_description: unknown
      canonical_url: unknown
      views: unknown
      published_at: unknown
      status: unknown
      is_featured: unknown
      author_id: number
      site_id: number
    }
    print_devices: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      mac_address: unknown
      location: unknown
      terminal: unknown
      status: unknown
      last_ping: unknown
      print_count: unknown
    }
    product_units: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      abbreviation: unknown
      type: unknown
      description: unknown
      is_default: unknown
      product_id: number
    }
    product_variants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      variant: unknown
      type: unknown
      description: unknown
      options: unknown
      status: unknown
      product_id: number
    }
    products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      price: unknown
      image_url: unknown
      is_available: unknown
      inventory_count: unknown
      preparation_time: unknown
      allergens: unknown
      nutritional_info: unknown
      category_id: number
      manufacturer_id: number
    }
    publication_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      status: unknown
      tier: unknown
      started_at: unknown
      ended_at: unknown
      team_id: number
      publication_id: number
      contact_id: number
    }
    publications: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      description: unknown
      status: unknown
      access: unknown
      settings: unknown
      team_id: number
      site_id: number
    }
    query_logs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      query: string
      normalized_query: string
      duration: unknown
      connection: unknown
      status: unknown
      error: string
      executed_at: unknown
      bindings: string
      trace: string
      model: unknown
      method: unknown
      file: unknown
      line: unknown
      memory_usage: unknown
      rows_affected: unknown
      transaction_id: unknown
      tags: unknown
      affected_tables: unknown
      indexes_used: unknown
      missing_indexes: unknown
      explain_plan: unknown
      optimization_suggestions: unknown
    }
    receipts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      printer: unknown
      document: unknown
      timestamp: unknown
      status: unknown
      size: unknown
      pages: unknown
      duration: unknown
      metadata: unknown
      print_device_id: number
    }
    recommendations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      partner_publication_id: unknown
      direction: unknown
      status: unknown
      reward_amount: unknown
      currency: unknown
      terms: unknown
      team_id: number
      publication_id: number
    }
    redirects: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      from_path: unknown
      to_path: unknown
      status_code: unknown
      source: unknown
      site_id: number
    }
    referrals: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      code: unknown
      referred_email_hash: unknown
      status: unknown
      reward: unknown
      qualified_at: unknown
      team_id: number
      publication_id: number
      contact_id: number
    }
    releases: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      version: unknown
      type: unknown
      status: unknown
      notes: unknown
      downloads: unknown
      author: unknown
    }
    requests: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      deleted_at: string | null
      method: unknown
      path: unknown
      status_code: unknown
      duration_ms: unknown
      ip_address: unknown
      memory_usage: unknown
      user_agent: unknown
      error_message: unknown
    }
    reviews: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rating: unknown
      title: unknown
      content: unknown
      is_verified_purchase: unknown
      is_approved: unknown
      is_featured: unknown
      helpful_votes: unknown
      unhelpful_votes: unknown
      purchase_date: unknown
      images: unknown
      product_id: number
      customer_id: number
    }
    segment_rules: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      field: unknown
      operator: unknown
      value: unknown
      position: unknown
      team_id: number
      segment_id: number
    }
    segment_snapshots: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      rule_checksum: unknown
      contact_ids: unknown
      contact_count: unknown
      source: unknown
      created_by: unknown
      team_id: number
      segment_id: number
    }
    segments: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      match_type: unknown
      estimated_count: unknown
      refreshed_at: unknown
      team_id: number
    }
    sender_domains: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      domain: unknown
      status: unknown
      selector: unknown
      dns_records: unknown
      verified_at: unknown
      last_checked_at: unknown
      team_id: number
    }
    sender_identities: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      channel: unknown
      name: unknown
      address: unknown
      reply_to: unknown
      status: unknown
      verification: unknown
      team_id: number
      sender_domain_id: number
    }
    shipping_methods: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      base_rate: unknown
      free_shipping: unknown
      status: unknown
    }
    shipping_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      weight_from: unknown
      weight_to: unknown
      rate: unknown
      shipping_method_id: number
      shipping_zone_id: number
    }
    shipping_zones: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      countries: unknown
      regions: unknown
      postal_codes: unknown
      status: unknown
      shipping_method_id: number
    }
    site_domains: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      domain: unknown
      is_primary: unknown
      verified_at: unknown
      ssl_status: unknown
      site_id: number
    }
    sites: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      subdomain: unknown
      status: unknown
      settings: unknown
      timezone: unknown
      team_id: number
    }
    sms_messages: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      body: unknown
      encoding: unknown
      segment_count: unknown
      stop_language_included: unknown
      quiet_hours_timezone: unknown
      revision: unknown
      team_id: number
      campaign_id: number
      sender_identity_id: number
    }
    sms_opt_outs: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      phone: unknown
      reason: unknown
      opted_out_at: unknown
    }
    social_accounts: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      provider: unknown
      provider_user_id: unknown
      provider_email: unknown
      user_id: number
    }
    social_posts: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      content: unknown
      platform: unknown
      status: unknown
      scheduled_at: unknown
      published_at: unknown
      likes: unknown
      shares: unknown
      comments: unknown
      reach: unknown
      image_url: unknown
      external_id: unknown
      user_id: number
    }
    sponsors: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      contact_email: unknown
      website: unknown
      status: unknown
      notes: unknown
      team_id: number
    }
    subscriber_emails: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: unknown
      source: unknown
      subscriber_id: number
    }
    subscribers: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      email: unknown
      status: unknown
      source: unknown
      unsubscribed_at: unknown
      user_id: number
    }
    subscriptions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      type: unknown
      plan: unknown
      provider_id: unknown
      provider_status: unknown
      unit_price: unknown
      provider_type: unknown
      provider_price_id: unknown
      quantity: unknown
      trial_ends_at: unknown
      ends_at: unknown
      last_used_at: unknown
      user_id: number
    }
    taggable_models: {
      // columns
      id: number
      tag_id: number
      taggable_id: number
      taggable_type: string
      created_at: string
      updated_at: string | null
    }
    tags: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      slug: unknown
      description: unknown
      color: unknown
    }
    tax_rates: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      rate: unknown
      type: unknown
      country: unknown
      region: unknown
      status: unknown
      is_default: unknown
      code: unknown
      exemptible: unknown
    }
    team_invitations: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      email: unknown
      role: unknown
      token_hash: unknown
      pending_key: unknown
      invited_by_user_id: unknown
      accepted_by_user_id: unknown
      status: unknown
      delivery_status: unknown
      delivery_error: unknown
      expires_at: unknown
      delivered_at: unknown
      accepted_at: unknown
    }
    team_members: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      team_id: number
      user_id: number
      role: unknown
      status: unknown
    }
    teams: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      description: unknown
      member_count: unknown
      status: unknown
    }
    transactions: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      amount: unknown
      status: unknown
      payment_method: unknown
      payment_details: unknown
      transaction_reference: unknown
      loyalty_points_earned: unknown
      loyalty_points_redeemed: unknown
      order_id: number
    }
    usage_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      meter: unknown
      quantity: unknown
      idempotency_key: unknown
      metadata: unknown
      occurred_at: unknown
      team_id: number
    }
    usage_meters: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      key: unknown
      quantity: unknown
      included_quantity: unknown
      period_start: unknown
      period_end: unknown
      team_id: number
    }
    users: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      password: unknown
      avatar: unknown
    }
    waitlist_products: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      phone: unknown
      quantity: unknown
      notification_preference: unknown
      source: unknown
      notes: unknown
      status: unknown
      notified_at: unknown
      purchased_at: unknown
      cancelled_at: unknown
      product_id: number
      customer_id: number
    }
    waitlist_restaurants: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      email: unknown
      phone: unknown
      party_size: unknown
      check_in_time: unknown
      table_preference: unknown
      status: unknown
      quoted_wait_time: unknown
      actual_wait_time: unknown
      queue_position: unknown
      seated_at: unknown
      no_show_at: unknown
      cancelled_at: unknown
      customer_id: number
    }
    webhook_endpoints: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      name: unknown
      provider: unknown
      direction: unknown
      url: unknown
      encrypted_secret: unknown
      events: unknown
      status: unknown
      team_id: number
    }
    webhook_events: {
      // columns
      id: number
      uuid: string
      created_at: string
      updated_at: string | null
      provider: unknown
      provider_event_id: unknown
      type: unknown
      status: unknown
      payload: unknown
      signature_verified: unknown
      attempts: unknown
      error: unknown
      processed_at: unknown
      team_id: number
      webhook_endpoint_id: number
    }
    websockets: {
      // columns
      id: number
      created_at: string
      updated_at: string | null
      type: unknown
      socket: unknown
      details: unknown
      time: unknown
    }
  }
}

export {}
