-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "timestamp" integer not null,
  "type" "logs_type_type" not null,
  "source" "logs_source_type" not null,
  "message" text not null,
  "project" varchar(255) not null,
  "stacktrace" text not null,
  "file" varchar(255) not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE INDEX IF NOT EXISTS "logs_timestamp_index" ON "logs" ("timestamp");
CREATE INDEX IF NOT EXISTS "logs_type_timestamp_index" ON "logs" ("type", "timestamp");
CREATE INDEX IF NOT EXISTS "logs_source_timestamp_index" ON "logs" ("source", "timestamp");
CREATE INDEX IF NOT EXISTS "logs_project_timestamp_index" ON "logs" ("project", "timestamp");
