-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "teams" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(100) not null,
  "description" varchar(500),
  "member_count" integer default 0,
  "status" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "teams_name_unique" ON "teams" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "teams_uuid_unique" ON "teams" ("uuid");
