-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "segments" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(120) not null,
  "description" varchar(500),
  "match_type" "segments_match_type_type" not null default 'all',
  "estimated_count" integer not null default 0,
  "refreshed_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "segments_team_name_unique" ON "segments" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "segments_uuid_unique" ON "segments" ("uuid");
