-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "auctions" (
  "id" BIGSERIAL PRIMARY KEY,
  "event_id" integer,
  "title" varchar(160) not null,
  "description" varchar(255),
  "status" "auctions_status_type" not null default 'draft',
  "currency" varchar(3) default 'USD',
  "goal_amount" integer,
  "opens_at" date not null,
  "closes_at" date not null,
  "anti_snipe_minutes" integer default 2,
  "extend_on_bid_window_minutes" integer default 2,
  "max_extensions" integer default 20,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "auctions_event_id_index" ON "auctions" ("event_id");
CREATE INDEX IF NOT EXISTS "auctions_status_index" ON "auctions" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "auctions_uuid_unique" ON "auctions" ("uuid");
