-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_webhook_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider" "email_webhook_events_provider_type" not null,
  "event_id" varchar(512) not null,
  "processed_at" timestamp not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "email_webhook_events_provider_event_unique" ON "email_webhook_events" ("provider", "event_id");
