-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "gated_resources" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(160) not null,
  "slug" varchar(160) not null,
  "access" "gated_resources_access_type" not null default 'subscriber',
  "segment_id" integer,
  "storage_key" varchar(500),
  "content" jsonb not null,
  "status" "gated_resources_status_type" not null default 'draft',
  "team_id" bigint REFERENCES "teams"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "product_id" bigint REFERENCES "products"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "gated_resources_team_slug_unique" ON "gated_resources" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "gated_resources_uuid_unique" ON "gated_resources" ("uuid");
