-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_definitions" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(160) not null,
  "slug" varchar(120) not null,
  "kind" "form_definitions_kind_type" not null default 'inline',
  "schema_document" jsonb not null,
  "double_opt_in" boolean not null default true,
  "status" "form_definitions_status_type" not null default 'draft',
  "team_id" bigint REFERENCES "teams"("id"),
  "site_id" bigint REFERENCES "sites"("id"),
  "audience_id" bigint REFERENCES "audiences"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "form_definitions_team_slug_unique" ON "form_definitions" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "form_definitions_uuid_unique" ON "form_definitions" ("uuid");
