-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_step_runs" (
  "id" BIGSERIAL PRIMARY KEY,
  "node_id" varchar(120) not null,
  "type" varchar(80) not null,
  "status" "automation_step_runs_status_type" not null default 'queued',
  "attempt" integer not null default 1,
  "idempotency_key" varchar(255) not null,
  "input" jsonb,
  "output" jsonb,
  "error" varchar(255),
  "available_at" timestamp,
  "started_at" timestamp,
  "completed_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "automation_run_id" bigint REFERENCES "automation_runs"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "automation_step_runs_idempotency_unique" ON "automation_step_runs" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_step_runs_uuid_unique" ON "automation_step_runs" ("uuid");
