-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reputation_mentions" (
  "id" BIGSERIAL PRIMARY KEY,
  "platform" "reputation_mentions_platform_type" not null,
  "kind" "reputation_mentions_kind_type" not null,
  "external_id" varchar(255) not null,
  "author_name" varchar(160),
  "author_handle" varchar(160),
  "body" text not null,
  "rating" integer,
  "sentiment" "reputation_mentions_sentiment_type" not null default 'unknown',
  "sentiment_score" integer not null default 0,
  "language" varchar(12),
  "url" varchar(500),
  "status" "reputation_mentions_status_type" not null default 'new',
  "responded_at" timestamp,
  "responded_by" integer,
  "raw" text not null,
  "posted_at" timestamp not null,
  "fetched_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "monitored_profile_id" bigint REFERENCES "monitored_profiles"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_mentions_profile_external_unique" ON "reputation_mentions" ("monitored_profile_id", "external_id");
CREATE INDEX IF NOT EXISTS "reputation_mentions_team_posted_index" ON "reputation_mentions" ("team_id", "posted_at");
CREATE INDEX IF NOT EXISTS "reputation_mentions_team_sentiment_index" ON "reputation_mentions" ("team_id", "sentiment", "posted_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_mentions_uuid_unique" ON "reputation_mentions" ("uuid");
