-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "ad_placements" (
  "id" BIGSERIAL PRIMARY KEY,
  "slot_key" varchar(120) not null,
  "rate" integer not null,
  "impressions" integer not null default 0,
  "clicks" integer not null default 0,
  "status" "ad_placements_status_type" not null default 'reserved',
  "team_id" bigint REFERENCES "teams"("id"),
  "advertiser_offer_id" bigint REFERENCES "advertiser_offers"("id"),
  "campaign_id" bigint REFERENCES "campaigns"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "ad_placements_team_status" ON "ad_placements" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "ad_placements_offer_slot_unique" ON "ad_placements" ("advertiser_offer_id", "slot_key");
CREATE UNIQUE INDEX IF NOT EXISTS "ad_placements_uuid_unique" ON "ad_placements" ("uuid");
