-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "receipts" (
  "id" BIGSERIAL PRIMARY KEY,
  "printer" varchar(100),
  "document" varchar(100) not null,
  "timestamp" timestamptz not null,
  "status" "receipts_status_type" not null,
  "size" integer default 0,
  "pages" integer default 0,
  "duration" integer default 0,
  "metadata" varchar(255) default '{}',
  "print_device_id" bigint REFERENCES "print_devices"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "receipts_uuid_unique" ON "receipts" ("uuid");
