-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_exports" (
  "id" BIGSERIAL PRIMARY KEY,
  "status" "audience_exports_status_type" not null default 'pending',
  "filters" jsonb not null,
  "storage_key" varchar(500),
  "row_count" integer not null default 0,
  "expires_at" timestamp,
  "completed_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "audience_id" bigint REFERENCES "audiences"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "audience_exports_team_status_index" ON "audience_exports" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_exports_uuid_unique" ON "audience_exports" ("uuid");
