-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "forms" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(255) not null,
  "handle" varchar(64) not null,
  "status" "forms_status_type" default 'draft',
  "settings" jsonb,
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "forms_site_handle_unique" ON "forms" ("site_id", "handle");
CREATE UNIQUE INDEX IF NOT EXISTS "forms_uuid_unique" ON "forms" ("uuid");
