-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "redirects" (
  "id" BIGSERIAL PRIMARY KEY,
  "from_path" text not null,
  "to_path" text not null,
  "status_code" integer default 301,
  "source" "redirects_source_type" default 'manual',
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "redirects_site_from_unique" ON "redirects" ("site_id", "from_path");
