-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "communication_suppressions" (
  "id" BIGSERIAL PRIMARY KEY,
  "recipient" varchar(255) not null,
  "channel" "communication_suppressions_channel_type" not null,
  "reason" "communication_suppressions_reason_type" not null,
  "source" varchar(120) not null,
  "suppressed_at" timestamp not null,
  "lifted_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "communication_suppressions_unique" ON "communication_suppressions" ("team_id", "channel", "recipient");
CREATE UNIQUE INDEX IF NOT EXISTS "communication_suppressions_uuid_unique" ON "communication_suppressions" ("uuid");
