-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "posts" (
  "id" BIGSERIAL PRIMARY KEY,
  "title" varchar(255) not null,
  "slug" varchar(255),
  "poster" varchar(255),
  "content" text not null,
  "excerpt" varchar(500),
  "focus_keyword" varchar(100),
  "meta_description" varchar(160),
  "canonical_url" varchar(255),
  "views" integer default 0,
  "published_at" timestamp,
  "status" "posts_status_type" not null default 'draft',
  "is_featured" integer,
  "author_id" bigint REFERENCES "authors"("id"),
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "posts_uuid_unique" ON "posts" ("uuid");
