-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "webhook_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider" varchar(60) not null,
  "provider_event_id" varchar(255) not null,
  "type" varchar(120) not null,
  "status" "webhook_events_status_type" not null default 'received',
  "payload" jsonb not null,
  "signature_verified" boolean not null default false,
  "attempts" integer not null default 0,
  "error" varchar(255),
  "processed_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "webhook_endpoint_id" bigint REFERENCES "webhook_endpoints"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_events_provider_unique" ON "webhook_events" ("provider", "provider_event_id");
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_events_uuid_unique" ON "webhook_events" ("uuid");
