-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reputation_alerts" (
  "id" BIGSERIAL PRIMARY KEY,
  "fingerprint" varchar(128) not null,
  "metric" "reputation_alerts_metric_type" not null,
  "severity" "reputation_alerts_severity_type" not null default 'warning',
  "observed_value" decimal(10,2) not null,
  "threshold_value" decimal(10,2) not null,
  "sample_size" integer not null default 0,
  "window_start" timestamp not null,
  "window_end" timestamp not null,
  "status" "reputation_alerts_status_type" not null default 'open',
  "context" text not null,
  "notified_channels" jsonb not null,
  "acknowledged_by" integer,
  "acknowledged_at" timestamp,
  "resolved_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "reputation_alert_rule_id" bigint REFERENCES "reputation_alert_rules"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alerts_team_fingerprint_unique" ON "reputation_alerts" ("team_id", "fingerprint");
CREATE INDEX IF NOT EXISTS "reputation_alerts_team_status_index" ON "reputation_alerts" ("team_id", "status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alerts_uuid_unique" ON "reputation_alerts" ("uuid");
