-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "usage_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "meter" varchar(60) not null,
  "quantity" integer not null,
  "source_type" varchar(120) not null,
  "source_id" varchar(120),
  "idempotency_key" varchar(255) not null,
  "provider_cost" integer not null default 0,
  "metadata" jsonb not null,
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "user_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_team_key_unique" ON "usage_events" ("team_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "usage_events_team_meter_index" ON "usage_events" ("team_id", "meter", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_uuid_unique" ON "usage_events" ("uuid");
