-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sender_identities" (
  "id" BIGSERIAL PRIMARY KEY,
  "channel" "sender_identities_channel_type" not null,
  "name" varchar(160) not null,
  "address" varchar(255) not null,
  "reply_to" varchar(255),
  "status" "sender_identities_status_type" not null default 'pending',
  "verification" jsonb,
  "team_id" bigint REFERENCES "teams"("id"),
  "sender_domain_id" bigint REFERENCES "sender_domains"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "sender_identities_team_address_unique" ON "sender_identities" ("team_id", "channel", "address");
CREATE UNIQUE INDEX IF NOT EXISTS "sender_identities_uuid_unique" ON "sender_identities" ("uuid");
