-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "team_invitations" (
  "id" BIGSERIAL PRIMARY KEY,
  "team_id" bigint not null REFERENCES "teams"("id"),
  "email" varchar(320) not null,
  "role" "team_invitations_role_type" not null default 'member',
  "token_hash" varchar(64) not null,
  "pending_key" varchar(384),
  "invited_by_user_id" integer,
  "accepted_by_user_id" integer,
  "status" "team_invitations_status_type" not null default 'pending',
  "delivery_status" "team_invitations_delivery_status_type" not null default 'pending',
  "delivery_error" text,
  "expires_at" timestamp not null,
  "delivered_at" timestamp,
  "accepted_at" timestamp,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "team_invitations_token_hash_unique" ON "team_invitations" ("token_hash");
CREATE UNIQUE INDEX IF NOT EXISTS "team_invitations_pending_key_unique" ON "team_invitations" ("pending_key");
CREATE INDEX IF NOT EXISTS "team_invitations_team_email_status_index" ON "team_invitations" ("team_id", "email", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "team_invitations_uuid_unique" ON "team_invitations" ("uuid");
