-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "requests" (
  "id" BIGSERIAL PRIMARY KEY,
  "method" "requests_method_type",
  "path" varchar(255),
  "status_code" integer,
  "duration_ms" integer,
  "ip_address" varchar(255),
  "memory_usage" integer,
  "user_agent" varchar(255),
  "error_message" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "deleted_at" timestamp
);
CREATE INDEX IF NOT EXISTS "requests_created_at_index" ON "requests" ("created_at");
CREATE INDEX IF NOT EXISTS "requests_duration_ms_index" ON "requests" ("duration_ms");
CREATE INDEX IF NOT EXISTS "requests_status_code_index" ON "requests" ("status_code");
