-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "campaign_recipients" (
  "id" BIGSERIAL PRIMARY KEY,
  "channel" "campaign_recipients_channel_type" not null,
  "address_hash" varchar(128) not null,
  "status" "campaign_recipients_status_type" not null default 'queued',
  "idempotency_key" varchar(128) not null,
  "snapshot" jsonb not null,
  "scheduled_at" varchar(255),
  "team_id" bigint REFERENCES "teams"("id"),
  "campaign_id" bigint REFERENCES "campaigns"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "campaign_variant_id" bigint REFERENCES "campaign_variants"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_recipients_unique" ON "campaign_recipients" ("campaign_id", "contact_id");
CREATE INDEX IF NOT EXISTS "campaign_recipients_team_status" ON "campaign_recipients" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_recipients_uuid_unique" ON "campaign_recipients" ("uuid");
