-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "boards" ADD COLUMN "team_id" bigint;
ALTER TABLE "boards" ADD CONSTRAINT "boards_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "teams"("id");
