-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "publication_members" (
  "id" BIGSERIAL PRIMARY KEY,
  "status" "publication_members_status_type" not null default 'pending',
  "tier" varchar(80) not null default 'free',
  "started_at" timestamp,
  "ended_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "publication_members_unique" ON "publication_members" ("publication_id", "contact_id");
CREATE INDEX IF NOT EXISTS "publication_members_team_status" ON "publication_members" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "publication_members_uuid_unique" ON "publication_members" ("uuid");
