-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sender_domains" (
  "id" BIGSERIAL PRIMARY KEY,
  "domain" varchar(253) not null,
  "status" "sender_domains_status_type" not null default 'pending',
  "selector" varchar(63) not null default 'mail',
  "dns_records" jsonb,
  "verified_at" timestamp,
  "last_checked_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "sender_domains_domain_unique" ON "sender_domains" ("domain");
CREATE UNIQUE INDEX IF NOT EXISTS "sender_domains_uuid_unique" ON "sender_domains" ("uuid");
