-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sites" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(255) not null,
  "subdomain" varchar(63) not null,
  "status" "sites_status_type" not null default 'active',
  "settings" jsonb,
  "timezone" varchar(64) default 'America/New_York',
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "sites_subdomain_unique" ON "sites" ("subdomain");
CREATE UNIQUE INDEX IF NOT EXISTS "sites_uuid_unique" ON "sites" ("uuid");
