-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "notification_deliveries" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint REFERENCES "users"("id"),
  "channel" varchar(255) not null,
  "recipient" text not null,
  "subject" varchar(255),
  "body" text not null,
  "status" varchar(255) not null default 'pending',
  "error" text,
  "metadata" text,
  "sent_at" timestamp,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
