-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "webhook_endpoints" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(120) not null,
  "provider" "webhook_endpoints_provider_type" not null,
  "direction" "webhook_endpoints_direction_type" not null default 'inbound',
  "url" text,
  "encrypted_secret" varchar(255) not null,
  "events" jsonb not null,
  "status" "webhook_endpoints_status_type" not null default 'active',
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_endpoints_team_name_unique" ON "webhook_endpoints" ("team_id", "provider", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_endpoints_uuid_unique" ON "webhook_endpoints" ("uuid");
