-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "data_retention_policies" (
  "id" BIGSERIAL PRIMARY KEY,
  "kind" "data_retention_policies_kind_type" not null,
  "retention_days" integer not null,
  "legal_hold" boolean not null default false,
  "jurisdiction" varchar(10),
  "status" "data_retention_policies_status_type" not null default 'active',
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "data_retention_policies_team_kind_unique" ON "data_retention_policies" ("team_id", "kind");
CREATE UNIQUE INDEX IF NOT EXISTS "data_retention_policies_uuid_unique" ON "data_retention_policies" ("uuid");
