-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_runs" (
  "id" BIGSERIAL PRIMARY KEY,
  "status" "automation_runs_status_type" not null default 'queued',
  "current_node_id" varchar(100),
  "version" integer not null default 1,
  "subject_type" varchar(80),
  "subject_id" varchar(120),
  "context" jsonb not null,
  "idempotency_key" varchar(255) not null,
  "started_at" timestamp,
  "finished_at" timestamp,
  "error" varchar(255),
  "team_id" bigint REFERENCES "teams"("id"),
  "automation_id" bigint REFERENCES "automations"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "automation_runs_idempotency_unique" ON "automation_runs" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_runs_uuid_unique" ON "automation_runs" ("uuid");
