-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "driver_pings" (
  "id" BIGSERIAL PRIMARY KEY,
  "latitude" integer not null,
  "longitude" integer not null,
  "heading" integer,
  "speed" integer default 0,
  "accuracy" integer,
  "recorded_at" timestamp not null,
  "driver_id" bigint REFERENCES "drivers"("id"),
  "delivery_route_id" bigint REFERENCES "delivery_routes"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "driver_pings_uuid_unique" ON "driver_pings" ("uuid");
