-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "segment_rules" (
  "id" BIGSERIAL PRIMARY KEY,
  "field" varchar(120) not null,
  "operator" "segment_rules_operator_type" not null,
  "value" jsonb,
  "position" integer not null default 0,
  "team_id" bigint REFERENCES "teams"("id"),
  "segment_id" bigint REFERENCES "segments"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "segment_rules_segment_position_index" ON "segment_rules" ("segment_id", "position");
CREATE UNIQUE INDEX IF NOT EXISTS "segment_rules_uuid_unique" ON "segment_rules" ("uuid");
