-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "usage_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "meter" "usage_events_meter_type" not null,
  "quantity" integer not null default 1,
  "idempotency_key" varchar(255) not null,
  "metadata" jsonb,
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_idempotency_unique" ON "usage_events" ("idempotency_key");
CREATE INDEX IF NOT EXISTS "usage_events_meter_period" ON "usage_events" ("team_id", "meter", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_uuid_unique" ON "usage_events" ("uuid");
