-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "advertiser_offers" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(180) not null,
  "creative" jsonb not null,
  "budget" integer not null,
  "currency" varchar(3) not null default 'USD',
  "starts_at" timestamp,
  "ends_at" timestamp,
  "status" "advertiser_offers_status_type" not null default 'draft',
  "team_id" bigint REFERENCES "teams"("id"),
  "sponsor_id" bigint REFERENCES "sponsors"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "advertiser_offers_team_status" ON "advertiser_offers" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "advertiser_offers_uuid_unique" ON "advertiser_offers" ("uuid");
