-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "entitlements" (
  "id" BIGSERIAL PRIMARY KEY,
  "key" varchar(120) not null,
  "value" jsonb not null,
  "source" "entitlements_source_type" not null default 'plan',
  "expires_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "subscription_id" bigint REFERENCES "subscriptions"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "entitlements_team_key_unique" ON "entitlements" ("team_id", "key");
CREATE UNIQUE INDEX IF NOT EXISTS "entitlements_uuid_unique" ON "entitlements" ("uuid");
