-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "tags" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(50) not null,
  "slug" varchar(50) not null,
  "description" varchar(255),
  "color" varchar(20),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "tags_name_unique" ON "tags" ("name");
CREATE UNIQUE INDEX IF NOT EXISTS "tags_slug_unique" ON "tags" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "tags_uuid_unique" ON "tags" ("uuid");
