-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "link_pages" (
  "id" BIGSERIAL PRIMARY KEY,
  "title" varchar(160) not null,
  "slug" varchar(160) not null,
  "bio" varchar(500),
  "links" jsonb not null,
  "theme" jsonb not null,
  "status" "link_pages_status_type" not null default 'draft',
  "team_id" bigint REFERENCES "teams"("id"),
  "site_id" bigint REFERENCES "sites"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "link_pages_team_slug_unique" ON "link_pages" ("team_id", "site_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "link_pages_uuid_unique" ON "link_pages" ("uuid");
