-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "delivery_routes" DROP COLUMN "driver_id";
ALTER TABLE "delivery_routes" ADD COLUMN "courier_id" bigint;
ALTER TABLE "delivery_routes" ADD CONSTRAINT "delivery_routes_courier_id_fk" FOREIGN KEY ("courier_id") REFERENCES "couriers"("id");
