-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_imports" (
  "id" BIGSERIAL PRIMARY KEY,
  "filename" varchar(255) not null,
  "storage_key" varchar(500) not null,
  "status" "audience_imports_status_type" not null default 'pending',
  "mapping" jsonb not null,
  "total_rows" integer not null default 0,
  "imported_rows" integer not null default 0,
  "rejected_rows" integer not null default 0,
  "error_report_key" varchar(500),
  "completed_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "audience_id" bigint REFERENCES "audiences"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "audience_imports_team_status_index" ON "audience_imports" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_imports_uuid_unique" ON "audience_imports" ("uuid");
