-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "pledges" (
  "id" BIGSERIAL PRIMARY KEY,
  "donor_name" varchar(160) not null,
  "donor_email" varchar(255) not null,
  "amount" integer not null,
  "level" varchar(40),
  "status" "pledges_status_type" not null default 'confirmed',
  "auction_id" bigint REFERENCES "auctions"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "pledges_auction_id_index" ON "pledges" ("auction_id");
CREATE INDEX IF NOT EXISTS "pledges_status_index" ON "pledges" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "pledges_uuid_unique" ON "pledges" ("uuid");
