-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "bids" (
  "id" BIGSERIAL PRIMARY KEY,
  "bidder_name" varchar(160) not null,
  "bidder_email" varchar(255) not null,
  "amount" integer not null,
  "max_amount" integer,
  "status" "bids_status_type" not null default 'leading',
  "placed_at" date not null,
  "auction_id" bigint REFERENCES "auctions"("id"),
  "auction_item_id" bigint REFERENCES "auction_items"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "bids_auction_item_id_index" ON "bids" ("auction_item_id");
CREATE INDEX IF NOT EXISTS "bids_auction_id_index" ON "bids" ("auction_id");
CREATE INDEX IF NOT EXISTS "bids_bidder_email_index" ON "bids" ("bidder_email");
CREATE INDEX IF NOT EXISTS "bids_status_index" ON "bids" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "bids_uuid_unique" ON "bids" ("uuid");
