-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reputation_alert_rules" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(120) not null,
  "metric" "reputation_alert_rules_metric_type" not null,
  "comparator" "reputation_alert_rules_comparator_type" not null,
  "threshold" decimal(10,2) not null,
  "window_minutes" integer not null default 1440,
  "minimum_sample_size" integer not null default 1,
  "platforms" jsonb not null,
  "severity" "reputation_alert_rules_severity_type" not null default 'warning',
  "channels" jsonb not null,
  "cooldown_minutes" integer not null default 360,
  "status" "reputation_alert_rules_status_type" not null default 'active',
  "next_evaluation_at" timestamp,
  "last_evaluated_at" timestamp,
  "last_triggered_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alert_rules_team_name_unique" ON "reputation_alert_rules" ("team_id", "name");
CREATE INDEX IF NOT EXISTS "reputation_alert_rules_due_index" ON "reputation_alert_rules" ("status", "next_evaluation_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alert_rules_uuid_unique" ON "reputation_alert_rules" ("uuid");
