-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_dead_letters" (
  "id" BIGSERIAL PRIMARY KEY,
  "node_id" varchar(120) not null,
  "payload" jsonb not null,
  "error_class" varchar(255) not null,
  "error_message" text not null,
  "attempts" integer not null default 1,
  "status" "automation_dead_letters_status_type" not null default 'open',
  "recovered_by" integer,
  "recovered_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "automation_id" bigint REFERENCES "automations"("id"),
  "automation_run_id" bigint REFERENCES "automation_runs"("id"),
  "automation_step_run_id" bigint REFERENCES "automation_step_runs"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "automation_dead_letters_team_status_index" ON "automation_dead_letters" ("team_id", "status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_dead_letters_uuid_unique" ON "automation_dead_letters" ("uuid");
