-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "loyalty_points" ADD COLUMN "customer_id" bigint;
ALTER TABLE "loyalty_points" ADD CONSTRAINT "loyalty_points_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "customers"("id");
