-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_identities" (
  "id" BIGSERIAL PRIMARY KEY,
  "channel" "contact_identities_channel_type" not null,
  "value" varchar(255) not null,
  "verified_at" timestamp,
  "is_primary" boolean not null default false,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "contact_identities_team_value_unique" ON "contact_identities" ("team_id", "channel", "value");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_identities_uuid_unique" ON "contact_identities" ("uuid");
