-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "monitored_profiles" (
  "id" BIGSERIAL PRIMARY KEY,
  "platform" "monitored_profiles_platform_type" not null,
  "kind" "monitored_profiles_kind_type" not null,
  "display_name" varchar(160) not null,
  "handle" varchar(160),
  "external_id" varchar(255) not null,
  "location_label" varchar(200),
  "profile_url" varchar(500),
  "status" "monitored_profiles_status_type" not null default 'unconfigured',
  "poll_interval_minutes" integer not null default 30,
  "next_poll_at" timestamp,
  "last_polled_at" timestamp,
  "last_mention_at" timestamp,
  "cursor" varchar(500),
  "consecutive_failures" integer not null default 0,
  "last_error" varchar(500),
  "team_id" bigint REFERENCES "teams"("id"),
  "integration_credential_id" bigint REFERENCES "integration_credentials"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "monitored_profiles_team_platform_external_unique" ON "monitored_profiles" ("team_id", "platform", "external_id");
CREATE INDEX IF NOT EXISTS "monitored_profiles_due_index" ON "monitored_profiles" ("status", "next_poll_at");
CREATE UNIQUE INDEX IF NOT EXISTS "monitored_profiles_uuid_unique" ON "monitored_profiles" ("uuid");
