-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "oauth_access_tokens" (
  "id" BIGSERIAL PRIMARY KEY,
  "tokenable_type" varchar(255),
  "tokenable_id" integer,
  "name" varchar(255),
  "token" varchar(255),
  "scopes" text,
  "revoked" boolean default false,
  "expires_at" varchar(255),
  "user_agent" varchar(255),
  "ip_address" varchar(45),
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
