-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "magic_link_tokens" (
  "id" BIGSERIAL PRIMARY KEY,
  "email" varchar(255) not null,
  "token" varchar(64) not null,
  "expires_at" timestamp not null,
  "consumed_at" timestamp,
  "redirect_to" text,
  "site_id" integer,
  "user_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "magic_link_tokens_token_unique" ON "magic_link_tokens" ("token");
CREATE UNIQUE INDEX IF NOT EXISTS "magic_link_tokens_token_unique" ON "magic_link_tokens" ("token");
