-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commerce_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "external_id" varchar(255) not null,
  "type" "commerce_events_type_type" not null,
  "amount" integer,
  "currency" varchar(3) default 'USD',
  "payload" jsonb not null,
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "commerce_connection_id" bigint REFERENCES "commerce_connections"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_events_provider_unique" ON "commerce_events" ("commerce_connection_id", "external_id");
CREATE INDEX IF NOT EXISTS "commerce_events_team_type_index" ON "commerce_events" ("team_id", "type", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_events_uuid_unique" ON "commerce_events" ("uuid");
