-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commerce_connections" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider" "commerce_connections_provider_type" not null,
  "name" varchar(120) not null,
  "external_account_id" varchar(255),
  "encrypted_credentials" varchar(255),
  "status" "commerce_connections_status_type" not null default 'pending',
  "cursor" varchar(255),
  "last_synced_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_connections_team_provider_unique" ON "commerce_connections" ("team_id", "provider", "external_account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_connections_uuid_unique" ON "commerce_connections" ("uuid");
