-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "social_accounts" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider" varchar(50) not null,
  "provider_user_id" varchar(255) not null,
  "provider_email" varchar(255),
  "user_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "social_accounts_provider_provider_user_id_unique" ON "social_accounts" ("provider", "provider_user_id");
CREATE INDEX IF NOT EXISTS "social_accounts_user_id_index" ON "social_accounts" ("user_id");
