-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_approvals" (
  "id" BIGSERIAL PRIMARY KEY,
  "action" varchar(100) not null,
  "payload" jsonb not null,
  "status" "automation_approvals_status_type" not null default 'pending',
  "requested_by" integer not null,
  "decided_by" integer,
  "reason" text,
  "expires_at" timestamp,
  "decided_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "automation_id" bigint REFERENCES "automations"("id"),
  "automation_run_id" bigint REFERENCES "automation_runs"("id"),
  "automation_step_run_id" bigint REFERENCES "automation_step_runs"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "automation_approvals_team_status_index" ON "automation_approvals" ("team_id", "status", "expires_at");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_approvals_uuid_unique" ON "automation_approvals" ("uuid");
