-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "subscriptions" (
  "id" BIGSERIAL PRIMARY KEY,
  "type" varchar(120) not null,
  "plan" varchar(100) not null,
  "provider_id" varchar(255) not null,
  "provider_status" varchar(100) not null,
  "unit_price" integer not null default 0,
  "provider_type" varchar(100) not null,
  "provider_price_id" varchar(255),
  "provider_customer_id" varchar(255),
  "quantity" integer not null default 1,
  "cancel_at_period_end" boolean not null default false,
  "trial_ends_at" timestamp,
  "ends_at" timestamp,
  "last_used_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "user_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptions_provider_id_unique" ON "subscriptions" ("provider_id");
CREATE INDEX IF NOT EXISTS "subscriptions_team_status_index" ON "subscriptions" ("team_id", "provider_status");
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptions_uuid_unique" ON "subscriptions" ("uuid");
