-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_submissions" (
  "id" BIGSERIAL PRIMARY KEY,
  "payload" jsonb not null,
  "dedupe_key" varchar(128) not null,
  "source_url" text,
  "ip_hash" varchar(128),
  "status" "form_submissions_status_type" not null default 'accepted',
  "team_id" bigint REFERENCES "teams"("id"),
  "form_definition_id" bigint REFERENCES "form_definitions"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "form_submissions_team_created" ON "form_submissions" ("team_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "form_submissions_dedupe_unique" ON "form_submissions" ("form_definition_id", "dedupe_key");
CREATE UNIQUE INDEX IF NOT EXISTS "form_submissions_uuid_unique" ON "form_submissions" ("uuid");
