-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "delivery_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "channel" "delivery_events_channel_type" not null,
  "type" "delivery_events_type_type" not null,
  "provider" varchar(60) not null,
  "provider_event_id" varchar(255) not null,
  "delivery_key" varchar(500) not null,
  "payload" jsonb not null,
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_events_provider_unique" ON "delivery_events" ("provider", "provider_event_id");
CREATE INDEX IF NOT EXISTS "delivery_events_team_occurred_index" ON "delivery_events" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_events_uuid_unique" ON "delivery_events" ("uuid");
