-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_fields" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(64) not null,
  "label" varchar(255) not null,
  "type" "form_fields_type_type" not null,
  "required" boolean default false,
  "position" integer default 0,
  "width" "form_fields_width_type" default 'full',
  "options" jsonb,
  "conditions" jsonb,
  "form_id" bigint REFERENCES "forms"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "form_fields_form_name_unique" ON "form_fields" ("form_id", "name");
