-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "campaign_sends" (
  "id" BIGSERIAL PRIMARY KEY,
  "campaign_id" bigint not null REFERENCES "campaigns"("id"),
  "subscriber_id" bigint REFERENCES "subscribers"("id"),
  "email_list_id" bigint REFERENCES "email_lists"("id"),
  "status" "campaign_sends_status_type" not null default 'queued',
  "channel" "campaign_sends_channel_type" not null default 'email',
  "recipient" varchar(255) not null,
  "idempotency_key" varchar(255) not null,
  "provider_message_id" varchar(255),
  "error" varchar(255),
  "sent_at" timestamp,
  "opened_at" timestamp,
  "clicked_at" timestamp,
  "delivered_at" timestamp,
  "failed_at" timestamp,
  "segments" integer,
  "cost" integer,
  "metadata" jsonb,
  "team_id" bigint REFERENCES "teams"("id"),
  "campaign_variant_id" bigint REFERENCES "campaign_variants"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_sends_idempotency_unique" ON "campaign_sends" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_sends_uuid_unique" ON "campaign_sends" ("uuid");
