-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "storage_items" (
  "id" BIGSERIAL PRIMARY KEY,
  "disk" varchar(64) not null,
  "path" text not null,
  "favorite" boolean default false,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "storage_items_disk_path_unique" ON "storage_items" ("disk", "path");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_items_uuid_unique" ON "storage_items" ("uuid");
