-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "data_requests" (
  "id" BIGSERIAL PRIMARY KEY,
  "type" "data_requests_type_type" not null,
  "status" "data_requests_status_type" not null default 'pending',
  "jurisdiction" varchar(80),
  "requested_at" timestamp not null,
  "completed_at" timestamp,
  "proof" jsonb,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "data_requests_team_status_index" ON "data_requests" ("team_id", "status", "requested_at");
CREATE UNIQUE INDEX IF NOT EXISTS "data_requests_uuid_unique" ON "data_requests" ("uuid");
