-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "podcasts" (
  "id" BIGSERIAL PRIMARY KEY,
  "title" varchar(180) not null,
  "slug" varchar(120) not null,
  "description" text,
  "author" varchar(160) not null,
  "explicit" boolean not null default false,
  "status" "podcasts_status_type" not null default 'draft',
  "team_id" bigint REFERENCES "teams"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "podcasts_team_slug_unique" ON "podcasts" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "podcasts_uuid_unique" ON "podcasts" ("uuid");
