-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "custom_fields" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(100) not null,
  "key" varchar(100) not null,
  "type" "custom_fields_type_type" not null,
  "options" jsonb,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "custom_fields_team_key_unique" ON "custom_fields" ("team_id", "key");
CREATE UNIQUE INDEX IF NOT EXISTS "custom_fields_uuid_unique" ON "custom_fields" ("uuid");
