-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_idempotency" (
  "id" BIGSERIAL PRIMARY KEY,
  "idempotency_key" varchar(255) not null,
  "message_id" varchar(512),
  "recipient" text,
  "subject" text,
  "provider" varchar(100),
  "success" boolean not null default true,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "email_idempotency_idempotency_key_unique" ON "email_idempotency" ("idempotency_key");
