-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_field_values" (
  "id" BIGSERIAL PRIMARY KEY,
  "value" jsonb,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "custom_field_id" bigint REFERENCES "custom_fields"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "contact_field_values_unique" ON "contact_field_values" ("team_id", "contact_id", "custom_field_id");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_field_values_uuid_unique" ON "contact_field_values" ("uuid");
