-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_suppressions" (
  "id" BIGSERIAL PRIMARY KEY,
  "email" varchar(320) not null,
  "type" "email_suppressions_type_type" not null,
  "reason" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "email_suppressions_email_type_unique" ON "email_suppressions" ("email", "type");
