-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "failed_jobs" (
  "id" BIGSERIAL PRIMARY KEY,
  "connection" varchar(100) not null,
  "queue" varchar(255) not null,
  "payload" varchar(255) not null,
  "exception" varchar(255) not null,
  "attempts" integer,
  "max_attempts" integer,
  "duration_ms" integer,
  "failed_at" date,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "failed_jobs_uuid_unique" ON "failed_jobs" ("uuid");
