-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "message_templates" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(120) not null,
  "channel" "message_templates_channel_type" not null,
  "subject" varchar(255),
  "document" jsonb not null,
  "plain_text" varchar(255),
  "revision" integer not null default 1,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "message_templates_team_name_unique" ON "message_templates" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "message_templates_uuid_unique" ON "message_templates" ("uuid");
