-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audiences" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(120) not null,
  "description" varchar(500),
  "channel" "audiences_channel_type" not null default 'all',
  "member_count" integer not null default 0,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "audiences_team_name_unique" ON "audiences" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "audiences_uuid_unique" ON "audiences" ("uuid");
