-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "referrals" (
  "id" BIGSERIAL PRIMARY KEY,
  "code" varchar(64) not null,
  "referred_email_hash" varchar(128) not null,
  "status" "referrals_status_type" not null default 'clicked',
  "reward" jsonb,
  "qualified_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "referrals_team_code_unique" ON "referrals" ("team_id", "code");
CREATE INDEX IF NOT EXISTS "referrals_team_status" ON "referrals" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "referrals_uuid_unique" ON "referrals" ("uuid");
