-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "episodes" (
  "id" BIGSERIAL PRIMARY KEY,
  "title" varchar(200) not null,
  "slug" varchar(120) not null,
  "summary" text,
  "audio_url" text not null,
  "duration_seconds" integer,
  "published_at" timestamp,
  "status" "episodes_status_type" not null default 'draft',
  "team_id" bigint REFERENCES "teams"("id"),
  "podcast_id" bigint REFERENCES "podcasts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "episodes_podcast_slug_unique" ON "episodes" ("podcast_id", "slug");
CREATE INDEX IF NOT EXISTS "episodes_team_published" ON "episodes" ("team_id", "published_at");
CREATE UNIQUE INDEX IF NOT EXISTS "episodes_uuid_unique" ON "episodes" ("uuid");
