-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "segment_snapshots" (
  "id" BIGSERIAL PRIMARY KEY,
  "rule_checksum" varchar(128) not null,
  "contact_ids" jsonb not null,
  "contact_count" integer not null default 0,
  "source" "segment_snapshots_source_type" not null default 'campaign',
  "created_by" integer not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "segment_id" bigint REFERENCES "segments"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "segment_snapshots_team_segment_index" ON "segment_snapshots" ("team_id", "segment_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "segment_snapshots_uuid_unique" ON "segment_snapshots" ("uuid");
