-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reviews" (
  "id" BIGSERIAL PRIMARY KEY,
  "rating" integer,
  "title" varchar(100),
  "content" text,
  "is_verified_purchase" boolean default false,
  "is_approved" boolean default false,
  "is_featured" boolean default false,
  "helpful_votes" integer default 0,
  "unhelpful_votes" integer default 0,
  "purchase_date" varchar(255),
  "images" varchar(255),
  "product_id" bigint REFERENCES "products"("id"),
  "customer_id" bigint REFERENCES "customers"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "reviews_uuid_unique" ON "reviews" ("uuid");
