-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "auction_items" (
  "id" BIGSERIAL PRIMARY KEY,
  "lot_number" integer not null,
  "title" varchar(160) not null,
  "description" varchar(255),
  "image_url" varchar(500),
  "category" varchar(60),
  "donor_name" varchar(160),
  "fair_market_value" integer,
  "starting_bid" integer not null,
  "min_increment" integer,
  "buy_now_price" integer,
  "reserve_price" integer,
  "status" "auction_items_status_type" not null default 'open',
  "closes_at" date,
  "extension_count" integer default 0,
  "auction_id" bigint REFERENCES "auctions"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "auction_items_auction_id_index" ON "auction_items" ("auction_id");
CREATE INDEX IF NOT EXISTS "auction_items_status_index" ON "auction_items" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "auction_items_uuid_unique" ON "auction_items" ("uuid");
