-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "storage_item_tasks" (
  "id" BIGSERIAL PRIMARY KEY,
  "disk" varchar(64) not null,
  "path" text not null,
  "kind" "storage_item_tasks_kind_type",
  "state" "storage_item_tasks_state_type" default 'queued',
  "attempts" integer default 0,
  "error" text,
  "started_at" varchar(255),
  "finished_at" varchar(255),
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "storage_item_tasks_disk_path_kind_unique" ON "storage_item_tasks" ("disk", "path", "kind");
CREATE UNIQUE INDEX IF NOT EXISTS "storage_item_tasks_uuid_unique" ON "storage_item_tasks" ("uuid");
