-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "integration_credentials" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider" "integration_credentials_provider_type" not null,
  "name" varchar(120) not null,
  "encrypted_value" varchar(255) not null,
  "last_four" varchar(4),
  "rotated_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "integration_credentials_team_provider_unique" ON "integration_credentials" ("team_id", "provider", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "integration_credentials_uuid_unique" ON "integration_credentials" ("uuid");
