-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "team_members" (
  "id" BIGSERIAL PRIMARY KEY,
  "team_id" bigint not null REFERENCES "teams"("id"),
  "user_id" bigint not null REFERENCES "users"("id"),
  "role" "team_members_role_type" not null default 'member',
  "status" "team_members_status_type" not null default 'active',
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "team_members_team_user_unique" ON "team_members" ("team_id", "user_id");
CREATE INDEX IF NOT EXISTS "team_members_user_status_index" ON "team_members" ("user_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "team_members_uuid_unique" ON "team_members" ("uuid");
