-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TYPE "couriers_status_type" AS ENUM ('active', 'on_delivery', 'on_break', 'offline');
CREATE TYPE "storage_item_tasks_kind_type" AS ENUM ('optimize', 'transcode', 'tag');
CREATE TYPE "storage_item_tasks_state_type" AS ENUM ('queued', 'running', 'done', 'failed');
CREATE TYPE "delivery_stops_type_type" AS ENUM ('pickup', 'dropoff');
