-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "categorizables" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(255) not null,
  "slug" varchar(255) not null,
  "description" varchar(255),
  "is_active" boolean not null default true,
  "categorizable_id" integer not null default 0,
  "categorizable_type" varchar(255) not null,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "categorizables_type_slug_unique" ON "categorizables" ("categorizable_type", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "categorizables_owner_slug_unique" ON "categorizables" ("categorizable_type", "categorizable_id", "slug");
