-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "pages" (
  "id" BIGSERIAL PRIMARY KEY,
  "title" varchar(255) not null,
  "slug" varchar(255),
  "path" text,
  "parent_id" integer,
  "template" varchar(255) not null,
  "blocks" jsonb,
  "meta_description" varchar(320),
  "status" "pages_status_type" default 'draft',
  "scheduled_at" timestamp,
  "views" integer default 0,
  "published_at" timestamp,
  "conversions" integer default 0,
  "author_id" bigint REFERENCES "authors"("id"),
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "pages_site_path_unique" ON "pages" ("site_id", "path");
CREATE UNIQUE INDEX IF NOT EXISTS "pages_uuid_unique" ON "pages" ("uuid");
