-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "publications" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(160) not null,
  "slug" varchar(120) not null,
  "description" text,
  "status" "publications_status_type" not null default 'draft',
  "access" "publications_access_type" not null default 'free',
  "settings" jsonb,
  "team_id" bigint REFERENCES "teams"("id"),
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "publications_team_slug_unique" ON "publications" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "publications_uuid_unique" ON "publications" ("uuid");
