-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "menu_items" (
  "id" BIGSERIAL PRIMARY KEY,
  "label" varchar(120) not null,
  "url" text,
  "target" "menu_items_target_type" default '_self',
  "parent_id" integer,
  "position" integer default 0,
  "visibility" "menu_items_visibility_type" default 'public',
  "menu_id" bigint REFERENCES "menus"("id"),
  "page_id" bigint REFERENCES "pages"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
