-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commissions" (
  "id" BIGSERIAL PRIMARY KEY,
  "kind" "commissions_kind_type" not null,
  "gross_amount" integer not null,
  "fee_basis_points" integer not null,
  "fee_amount" integer not null,
  "net_amount" integer not null,
  "currency" varchar(3) not null default 'usd',
  "status" "commissions_status_type" not null default 'pending',
  "payable_at" timestamp,
  "paid_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "earning_id" bigint REFERENCES "earnings"("id"),
  "referral_id" bigint REFERENCES "referrals"("id"),
  "recommendation_id" bigint REFERENCES "recommendations"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "commissions_team_status_index" ON "commissions" ("team_id", "status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "commissions_uuid_unique" ON "commissions" ("uuid");
