-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "usage_meters" (
  "id" BIGSERIAL PRIMARY KEY,
  "key" "usage_meters_key_type" not null,
  "quantity" integer not null default 0,
  "included_quantity" integer,
  "period_start" timestamp not null,
  "period_end" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "usage_meters_team_period_unique" ON "usage_meters" ("team_id", "key", "period_start");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_meters_uuid_unique" ON "usage_meters" ("uuid");
