-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "recommendations" (
  "id" BIGSERIAL PRIMARY KEY,
  "partner_publication_id" integer not null,
  "direction" "recommendations_direction_type" not null,
  "status" "recommendations_status_type" not null default 'pending',
  "reward_amount" integer not null default 0,
  "currency" varchar(3) not null default 'usd',
  "terms" jsonb not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "recommendations_partner_unique" ON "recommendations" ("team_id", "publication_id", "partner_publication_id");
CREATE UNIQUE INDEX IF NOT EXISTS "recommendations_uuid_unique" ON "recommendations" ("uuid");
