-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audit_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "action" varchar(160) not null,
  "subject_type" varchar(120),
  "subject_id" varchar(120),
  "metadata" jsonb not null,
  "ip_address" varchar(45),
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "user_id" bigint REFERENCES "users"("id"),
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "audit_events_team_occurred_index" ON "audit_events" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "audit_events_uuid_unique" ON "audit_events" ("uuid");
