-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "menus" (
  "id" BIGSERIAL PRIMARY KEY,
  "handle" varchar(64) not null,
  "name" varchar(255) not null,
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "menus_site_handle_unique" ON "menus" ("site_id", "handle");
