-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "earnings" (
  "id" BIGSERIAL PRIMARY KEY,
  "source_type" "earnings_source_type_type" not null,
  "source_id" varchar(128) not null,
  "gross_amount" integer not null,
  "fee_amount" integer not null,
  "net_amount" integer not null,
  "currency" varchar(3) not null default 'USD',
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "ad_placement_id" bigint REFERENCES "ad_placements"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "earnings_team_occurred" ON "earnings" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "earnings_source_unique" ON "earnings" ("source_type", "source_id");
CREATE UNIQUE INDEX IF NOT EXISTS "earnings_uuid_unique" ON "earnings" ("uuid");
