-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "payouts" (
  "id" BIGSERIAL PRIMARY KEY,
  "provider_id" varchar(255),
  "amount" integer not null,
  "currency" varchar(3) not null default 'USD',
  "status" "payouts_status_type" not null default 'pending',
  "scheduled_at" timestamp,
  "paid_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "payouts_team_status" ON "payouts" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "payouts_provider_id_unique" ON "payouts" ("provider_id");
CREATE UNIQUE INDEX IF NOT EXISTS "payouts_uuid_unique" ON "payouts" ("uuid");
