-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_tags" (
  "id" BIGSERIAL PRIMARY KEY,
  "source" varchar(100) not null default 'manual',
  "applied_by" integer,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "audience_tag_id" bigint REFERENCES "audience_tags"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "contact_tags_unique" ON "contact_tags" ("team_id", "contact_id", "audience_tag_id");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_tags_uuid_unique" ON "contact_tags" ("uuid");
