-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sms_opt_outs" (
  "id" BIGSERIAL PRIMARY KEY,
  "phone" varchar(20) not null,
  "reason" varchar(64) default 'stop-keyword',
  "opted_out_at" timestamp not null,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_opt_outs_phone_unique" ON "sms_opt_outs" ("phone");
CREATE UNIQUE INDEX IF NOT EXISTS "sms_opt_outs_phone_unique" ON "sms_opt_outs" ("phone");
