-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "ad_inventory" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(160) not null,
  "format" "ad_inventory_format_type" not null,
  "position" varchar(100) not null,
  "rate" integer not null,
  "currency" varchar(3) not null default 'usd',
  "capacity" integer not null default 1,
  "status" "ad_inventory_status_type" not null default 'active',
  "team_id" bigint REFERENCES "teams"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "ad_inventory_team_publication_index" ON "ad_inventory" ("team_id", "publication_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "ad_inventory_uuid_unique" ON "ad_inventory" ("uuid");
