-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "pledges" ADD COLUMN "customer_id" bigint;
ALTER TABLE "pledges" ADD CONSTRAINT "pledges_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "customers"("id");
