-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "landing_pages" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(160) not null,
  "slug" varchar(160) not null,
  "status" "landing_pages_status_type" not null default 'draft',
  "document" jsonb not null,
  "seo" jsonb not null,
  "published_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "site_id" bigint REFERENCES "sites"("id"),
  "publication_id" bigint REFERENCES "publications"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "landing_pages_team_slug_unique" ON "landing_pages" ("team_id", "site_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "landing_pages_uuid_unique" ON "landing_pages" ("uuid");
