-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "message_blocks" (
  "id" BIGSERIAL PRIMARY KEY,
  "type" "message_blocks_type_type" not null,
  "content" jsonb not null,
  "styles" jsonb,
  "position" integer not null default 0,
  "reusable" boolean not null default false,
  "team_id" bigint REFERENCES "teams"("id"),
  "message_template_id" bigint REFERENCES "message_templates"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "message_blocks_template_position_index" ON "message_blocks" ("message_template_id", "position");
CREATE UNIQUE INDEX IF NOT EXISTS "message_blocks_uuid_unique" ON "message_blocks" ("uuid");
