-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "courier_pings" (
  "id" BIGSERIAL PRIMARY KEY,
  "latitude" integer not null,
  "longitude" integer not null,
  "heading" integer,
  "speed" integer default 0,
  "accuracy" integer,
  "recorded_at" timestamp not null,
  "courier_id" bigint REFERENCES "couriers"("id"),
  "delivery_route_id" bigint REFERENCES "delivery_routes"("id"),
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "courier_pings_uuid_unique" ON "courier_pings" ("uuid");
