-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automations" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(255) not null,
  "status" "automations_status_type" not null default 'draft',
  "version" integer not null default 1,
  "trigger" jsonb not null,
  "graph" jsonb not null,
  "published_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "automations_uuid_unique" ON "automations" ("uuid");
