-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_merges" (
  "id" BIGSERIAL PRIMARY KEY,
  "source_contact_uuid" varchar(64) not null,
  "snapshot" jsonb not null,
  "merged_by_user_id" integer not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "contact_merges_team_created_index" ON "contact_merges" ("team_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_merges_uuid_unique" ON "contact_merges" ("uuid");
