-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_messages" (
  "id" BIGSERIAL PRIMARY KEY,
  "subject" varchar(255) not null,
  "preheader" varchar(255),
  "from_name" varchar(120) not null,
  "from_address" varchar(255) not null,
  "reply_to" varchar(255),
  "document" jsonb not null,
  "html" varchar(255),
  "text" varchar(255),
  "revision" integer not null default 1,
  "team_id" bigint REFERENCES "teams"("id"),
  "campaign_id" bigint REFERENCES "campaigns"("id"),
  "message_template_id" bigint REFERENCES "message_templates"("id"),
  "sender_identity_id" bigint REFERENCES "sender_identities"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "email_messages_team_campaign_index" ON "email_messages" ("team_id", "campaign_id");
CREATE UNIQUE INDEX IF NOT EXISTS "email_messages_uuid_unique" ON "email_messages" ("uuid");
