-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_versions" (
  "id" BIGSERIAL PRIMARY KEY,
  "version" integer not null,
  "graph" jsonb not null,
  "checksum" varchar(128) not null,
  "published_by" integer not null,
  "published_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "automation_id" bigint REFERENCES "automations"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "automation_versions_unique" ON "automation_versions" ("automation_id", "version");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_versions_uuid_unique" ON "automation_versions" ("uuid");
