-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "mail_preferences" (
  "id" BIGSERIAL PRIMARY KEY,
  "mailbox" varchar(320) not null,
  "account_name" varchar(255) not null default 'Stacks',
  "signature" text,
  "display_density" "mail_preferences_display_density_type" not null default 'default',
  "theme" "mail_preferences_theme_type" not null default 'system',
  "language" "mail_preferences_language_type" not null default 'en',
  "default_reply_behavior" "mail_preferences_default_reply_behavior_type" not null default 'replyAll',
  "send_and_archive" boolean not null default true,
  "auto_advance" "mail_preferences_auto_advance_type" not null default 'newer',
  "desktop_notifications" boolean not null default true,
  "notification_sound" "mail_preferences_notification_sound_type" not null default 'default',
  "notification_preview" boolean not null default true,
  "filters" varchar(255) not null default '[]',
  "blocked_senders" varchar(255) not null default '[]',
  "labels" varchar(255) not null default '[]',
  "load_remote_images" boolean not null default false,
  "show_external_content" boolean not null default false,
  "vacation_enabled" boolean not null default false,
  "vacation_start_date" varchar(255),
  "vacation_end_date" varchar(255),
  "vacation_subject" varchar(255),
  "vacation_message" text,
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "mail_preferences_mailbox_unique" ON "mail_preferences" ("mailbox");
