-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sms_messages" (
  "id" BIGSERIAL PRIMARY KEY,
  "body" text not null,
  "encoding" "sms_messages_encoding_type" not null default 'gsm7',
  "segment_count" integer not null default 1,
  "stop_language_included" boolean not null default true,
  "quiet_hours_timezone" varchar(100) not null default 'recipient',
  "revision" integer not null default 1,
  "team_id" bigint REFERENCES "teams"("id"),
  "campaign_id" bigint REFERENCES "campaigns"("id"),
  "sender_identity_id" bigint REFERENCES "sender_identities"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "sms_messages_team_campaign_index" ON "sms_messages" ("team_id", "campaign_id");
CREATE UNIQUE INDEX IF NOT EXISTS "sms_messages_uuid_unique" ON "sms_messages" ("uuid");
