-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "consent_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "recipient" varchar(255) not null,
  "channel" "consent_events_channel_type" not null,
  "action" "consent_events_action_type" not null,
  "purpose" varchar(120) not null,
  "source" varchar(120) not null,
  "jurisdiction" varchar(80),
  "policy_version" varchar(40) not null,
  "idempotency_key" varchar(255),
  "proof" jsonb,
  "ip_address" varchar(45),
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "consent_events_idempotency_unique" ON "consent_events" ("team_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "consent_events_lookup" ON "consent_events" ("team_id", "channel", "recipient", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "consent_events_uuid_unique" ON "consent_events" ("uuid");
