-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_memberships" (
  "id" BIGSERIAL PRIMARY KEY,
  "status" "audience_memberships_status_type" not null default 'active',
  "joined_at" timestamp not null,
  "left_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "audience_id" bigint REFERENCES "audiences"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "audience_memberships_unique" ON "audience_memberships" ("audience_id", "contact_id");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_memberships_uuid_unique" ON "audience_memberships" ("uuid");
