-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sponsors" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(180) not null,
  "contact_email" varchar(255) not null,
  "website" text,
  "status" "sponsors_status_type" not null default 'prospect',
  "notes" text,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "sponsors_team_name" ON "sponsors" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "sponsors_uuid_unique" ON "sponsors" ("uuid");
