-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
ALTER TABLE "failed_jobs" ALTER COLUMN "payload" DROP DEFAULT;
ALTER TABLE "failed_jobs" ALTER COLUMN "payload" TYPE text USING "payload"::text;
ALTER TABLE "failed_jobs" ALTER COLUMN "payload" SET NOT NULL;
ALTER TABLE "failed_jobs" ALTER COLUMN "exception" DROP DEFAULT;
ALTER TABLE "failed_jobs" ALTER COLUMN "exception" TYPE text USING "exception"::text;
ALTER TABLE "failed_jobs" ALTER COLUMN "exception" SET NOT NULL;
ALTER TABLE "jobs" ALTER COLUMN "payload" DROP DEFAULT;
ALTER TABLE "jobs" ALTER COLUMN "payload" TYPE text USING "payload"::text;
ALTER TABLE "jobs" ALTER COLUMN "payload" SET NOT NULL;
