-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "campaign_variants" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(80) not null,
  "subject" varchar(255),
  "content" jsonb not null,
  "allocation" integer not null default 50,
  "sent_count" integer not null default 0,
  "open_count" integer not null default 0,
  "click_count" integer not null default 0,
  "conversion_count" integer not null default 0,
  "is_winner" boolean not null default false,
  "team_id" bigint REFERENCES "teams"("id"),
  "campaign_id" bigint REFERENCES "campaigns"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_variants_name_unique" ON "campaign_variants" ("campaign_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_variants_uuid_unique" ON "campaign_variants" ("uuid");
