-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contacts" (
  "id" BIGSERIAL PRIMARY KEY,
  "email" varchar(255),
  "phone" varchar(32),
  "first_name" varchar(100),
  "last_name" varchar(100),
  "status" "contacts_status_type" not null default 'active',
  "source" varchar(100) not null default 'manual',
  "properties" jsonb,
  "last_engaged_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "contacts_team_email_unique" ON "contacts" ("team_id", "email");
CREATE INDEX IF NOT EXISTS "contacts_team_status_index" ON "contacts" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "contacts_uuid_unique" ON "contacts" ("uuid");
