-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "page_revisions" (
  "id" BIGSERIAL PRIMARY KEY,
  "revision" integer not null,
  "title" varchar(255) not null,
  "blocks" jsonb,
  "meta_description" varchar(320),
  "note" varchar(500),
  "page_id" bigint REFERENCES "pages"("id"),
  "author_id" bigint REFERENCES "authors"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "page_revisions_page_revision_unique" ON "page_revisions" ("page_id", "revision");
