-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "attribution_events" (
  "id" BIGSERIAL PRIMARY KEY,
  "kind" "attribution_events_kind_type" not null,
  "source" varchar(120) not null,
  "medium" varchar(120),
  "campaign_key" varchar(160),
  "revenue" integer,
  "currency" varchar(3),
  "dedupe_key" varchar(128) not null,
  "occurred_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "contact_id" bigint REFERENCES "contacts"("id"),
  "commerce_event_id" bigint REFERENCES "commerce_events"("id"),
  "campaign_id" bigint REFERENCES "campaigns"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "attribution_events_team_occurred" ON "attribution_events" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "attribution_events_dedupe_unique" ON "attribution_events" ("team_id", "dedupe_key");
CREATE UNIQUE INDEX IF NOT EXISTS "attribution_events_uuid_unique" ON "attribution_events" ("uuid");
