-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "referral_codes" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" bigint not null REFERENCES "users"("id"),
  "code" varchar(24) not null,
  "created_at" timestamp not null default (now() AT TIME ZONE 'utc'),
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "referral_codes_user_id_unique" ON "referral_codes" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "referral_codes_code_unique" ON "referral_codes" ("code");
