-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "delivery_stops" (
  "id" BIGSERIAL PRIMARY KEY,
  "sequence" integer not null default 1,
  "status" "delivery_stops_status_type" not null default 'pending',
  "address" varchar(255) not null,
  "latitude" integer,
  "longitude" integer,
  "recipient_name" varchar(255),
  "recipient_phone" varchar(40),
  "eta_at" timestamp,
  "notified_nearby_at" timestamp,
  "arrived_at" timestamp,
  "completed_at" timestamp,
  "notes" text,
  "delivery_route_id" bigint REFERENCES "delivery_routes"("id"),
  "order_id" bigint REFERENCES "orders"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_stops_uuid_unique" ON "delivery_stops" ("uuid");
