-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "ai_generations" (
  "id" BIGSERIAL PRIMARY KEY,
  "purpose" "ai_generations_purpose_type" not null,
  "idempotency_key" varchar(128) not null,
  "model" varchar(255) not null,
  "prompt_hash" varchar(128) not null,
  "provenance" jsonb not null,
  "output" text not null,
  "input_tokens" integer not null default 0,
  "output_tokens" integer not null default 0,
  "cost" integer not null default 0,
  "status" "ai_generations_status_type" not null default 'draft',
  "failure_reason" varchar(120),
  "approved_by" integer,
  "approved_at" timestamp,
  "team_id" bigint REFERENCES "teams"("id"),
  "user_id" bigint REFERENCES "users"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE INDEX IF NOT EXISTS "ai_generations_team_created_index" ON "ai_generations" ("team_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "ai_generations_team_idempotency_unique" ON "ai_generations" ("team_id", "idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "ai_generations_uuid_unique" ON "ai_generations" ("uuid");
