-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "site_domains" (
  "id" BIGSERIAL PRIMARY KEY,
  "domain" varchar(253) not null,
  "is_primary" boolean default false,
  "verified_at" timestamp,
  "ssl_status" "site_domains_ssl_status_type" default 'pending',
  "site_id" bigint REFERENCES "sites"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
CREATE UNIQUE INDEX IF NOT EXISTS "site_domains_domain_unique" ON "site_domains" ("domain");
