-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_tags" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" varchar(80) not null,
  "color" varchar(32) not null default 'coral',
  "team_id" bigint REFERENCES "teams"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "audience_tags_team_name_unique" ON "audience_tags" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_tags_uuid_unique" ON "audience_tags" ("uuid");
