-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "delivery_attempts" (
  "id" BIGSERIAL PRIMARY KEY,
  "channel" "delivery_attempts_channel_type" not null,
  "provider" varchar(100) not null,
  "provider_message_id" varchar(255),
  "idempotency_key" varchar(255) not null,
  "attempt" integer not null default 1,
  "status" "delivery_attempts_status_type" not null default 'pending',
  "retry_class" "delivery_attempts_retry_class_type",
  "error_code" varchar(100),
  "error_message" text,
  "retry_at" timestamp,
  "attempted_at" timestamp not null,
  "team_id" bigint REFERENCES "teams"("id"),
  "campaign_recipient_id" bigint REFERENCES "campaign_recipients"("id"),
  "campaign_send_id" bigint REFERENCES "campaign_sends"("id"),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp,
  "uuid" varchar(255)
);
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_attempts_idempotency_unique" ON "delivery_attempts" ("team_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "delivery_attempts_status_retry_index" ON "delivery_attempts" ("team_id", "status", "retry_at");
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_attempts_uuid_unique" ON "delivery_attempts" ("uuid");
