-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_identities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms', 'push', 'external')) not null,
  "value" TEXT not null,
  "verified_at" TEXT,
  "is_primary" INTEGER not null default 0,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "contact_identities_team_value_unique" ON "contact_identities" ("team_id", "channel", "value");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_identities_uuid_unique" ON "contact_identities" ("uuid");
