-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE INDEX IF NOT EXISTS "query_logs_executed_at_index" ON "query_logs" ("executed_at");
CREATE INDEX IF NOT EXISTS "query_logs_status_index" ON "query_logs" ("status");
CREATE INDEX IF NOT EXISTS "query_logs_duration_index" ON "query_logs" ("duration");
