-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_tags" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "color" TEXT not null default 'coral',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "audience_tags_team_name_unique" ON "audience_tags" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_tags_uuid_unique" ON "audience_tags" ("uuid");
