-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "ai_generations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "purpose" TEXT CHECK ("purpose" IN ('writing', 'segmentation', 'summary', 'optimization', 'recommendation')) not null,
  "model" TEXT not null,
  "prompt_hash" TEXT not null,
  "provenance" TEXT not null,
  "output" TEXT not null,
  "input_tokens" INTEGER not null default 0,
  "output_tokens" INTEGER not null default 0,
  "cost" INTEGER not null default 0,
  "status" TEXT CHECK ("status" IN ('draft', 'approved', 'rejected', 'published')) not null default 'draft',
  "approved_by" INTEGER,
  "approved_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "ai_generations_team_created_index" ON "ai_generations" ("team_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "ai_generations_uuid_unique" ON "ai_generations" ("uuid");
