-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_imports" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "filename" TEXT not null,
  "storage_key" TEXT not null,
  "status" TEXT CHECK ("status" IN ('pending', 'validating', 'processing', 'completed', 'failed')) not null default 'pending',
  "mapping" TEXT not null,
  "total_rows" INTEGER not null default 0,
  "imported_rows" INTEGER not null default 0,
  "rejected_rows" INTEGER not null default 0,
  "error_report_key" TEXT,
  "completed_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "audience_id" INTEGER REFERENCES "audiences"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "audience_imports_team_status_index" ON "audience_imports" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_imports_uuid_unique" ON "audience_imports" ("uuid");
