-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "usage_meters" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "key" TEXT CHECK ("key" IN ('contacts', 'emails', 'sms_segments', 'ai_generations', 'custom_domains')) not null,
  "quantity" INTEGER not null default 0,
  "included_quantity" INTEGER,
  "period_start" TEXT not null,
  "period_end" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "usage_meters_team_period_unique" ON "usage_meters" ("team_id", "key", "period_start");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_meters_uuid_unique" ON "usage_meters" ("uuid");
