-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "episodes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT not null,
  "slug" TEXT not null,
  "summary" TEXT,
  "audio_url" TEXT not null,
  "duration_seconds" INTEGER,
  "published_at" TEXT,
  "status" TEXT CHECK ("status" IN ('draft', 'scheduled', 'published', 'archived')) not null default 'draft',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "podcast_id" INTEGER REFERENCES "podcasts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "episodes_podcast_slug_unique" ON "episodes" ("podcast_id", "slug");
CREATE INDEX IF NOT EXISTS "episodes_team_published" ON "episodes" ("team_id", "published_at");
CREATE UNIQUE INDEX IF NOT EXISTS "episodes_uuid_unique" ON "episodes" ("uuid");
