-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "recommendations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "partner_publication_id" INTEGER not null,
  "direction" TEXT CHECK ("direction" IN ('outbound', 'inbound', 'exchange')) not null,
  "status" TEXT CHECK ("status" IN ('pending', 'active', 'paused', 'declined', 'ended')) not null default 'pending',
  "reward_amount" INTEGER not null default 0,
  "currency" TEXT not null default 'usd',
  "terms" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "recommendations_partner_unique" ON "recommendations" ("team_id", "publication_id", "partner_publication_id");
CREATE UNIQUE INDEX IF NOT EXISTS "recommendations_uuid_unique" ON "recommendations" ("uuid");
