-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "kind" TEXT CHECK ("kind" IN ('referral', 'recommendation', 'sponsorship', 'affiliate')) not null,
  "gross_amount" INTEGER not null,
  "fee_basis_points" INTEGER not null,
  "fee_amount" INTEGER not null,
  "net_amount" INTEGER not null,
  "currency" TEXT not null default 'usd',
  "status" TEXT CHECK ("status" IN ('pending', 'approved', 'payable', 'paid', 'reversed')) not null default 'pending',
  "payable_at" TEXT,
  "paid_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "earning_id" INTEGER REFERENCES "earnings"("id"),
  "referral_id" INTEGER REFERENCES "referrals"("id"),
  "recommendation_id" INTEGER REFERENCES "recommendations"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "commissions_team_status_index" ON "commissions" ("team_id", "status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "commissions_uuid_unique" ON "commissions" ("uuid");
