-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sender_identities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms')) not null,
  "name" TEXT not null,
  "address" TEXT not null,
  "reply_to" TEXT,
  "status" TEXT CHECK ("status" IN ('pending', 'verified', 'disabled', 'failed')) not null default 'pending',
  "verification" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "sender_domain_id" INTEGER REFERENCES "sender_domains"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "sender_identities_team_address_unique" ON "sender_identities" ("team_id", "channel", "address");
CREATE UNIQUE INDEX IF NOT EXISTS "sender_identities_uuid_unique" ON "sender_identities" ("uuid");
