-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reputation_mentions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "platform" TEXT CHECK ("platform" IN ('google_business', 'yelp', 'facebook', 'instagram', 'x', 'tiktok', 'linkedin', 'youtube', 'trustpilot', 'reddit')) not null,
  "kind" TEXT CHECK ("kind" IN ('review', 'comment', 'mention', 'question')) not null,
  "external_id" TEXT not null,
  "author_name" TEXT,
  "author_handle" TEXT,
  "body" TEXT not null,
  "rating" INTEGER,
  "sentiment" TEXT CHECK ("sentiment" IN ('positive', 'neutral', 'negative', 'unknown')) not null default 'unknown',
  "sentiment_score" INTEGER not null default 0,
  "language" TEXT,
  "url" TEXT,
  "status" TEXT CHECK ("status" IN ('new', 'triaged', 'responded', 'ignored')) not null default 'new',
  "responded_at" TEXT,
  "responded_by" INTEGER,
  "raw" TEXT not null,
  "posted_at" TEXT not null,
  "fetched_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "monitored_profile_id" INTEGER REFERENCES "monitored_profiles"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_mentions_profile_external_unique" ON "reputation_mentions" ("monitored_profile_id", "external_id");
CREATE INDEX IF NOT EXISTS "reputation_mentions_team_posted_index" ON "reputation_mentions" ("team_id", "posted_at");
CREATE INDEX IF NOT EXISTS "reputation_mentions_team_sentiment_index" ON "reputation_mentions" ("team_id", "sentiment", "posted_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_mentions_uuid_unique" ON "reputation_mentions" ("uuid");
