-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE UNIQUE INDEX IF NOT EXISTS "team_members_team_user_unique" ON "team_members" ("team_id", "user_id");
CREATE INDEX IF NOT EXISTS "team_members_user_status_index" ON "team_members" ("user_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "team_members_uuid_unique" ON "team_members" ("uuid");
