-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "earnings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "source_type" TEXT CHECK ("source_type" IN ('paid_publication', 'sponsorship', 'recommendation', 'digital_product', 'referral')) not null,
  "source_id" TEXT not null,
  "gross_amount" INTEGER not null,
  "fee_amount" INTEGER not null,
  "net_amount" INTEGER not null,
  "currency" TEXT not null default 'USD',
  "occurred_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "ad_placement_id" INTEGER REFERENCES "ad_placements"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "earnings_team_occurred" ON "earnings" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "earnings_source_unique" ON "earnings" ("source_type", "source_id");
CREATE UNIQUE INDEX IF NOT EXISTS "earnings_uuid_unique" ON "earnings" ("uuid");
