-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "message_templates" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms', 'landing_page')) not null,
  "subject" TEXT,
  "document" TEXT not null,
  "plain_text" TEXT,
  "revision" INTEGER not null default 1,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "message_templates_team_name_unique" ON "message_templates" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "message_templates_uuid_unique" ON "message_templates" ("uuid");
