-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reputation_alert_rules" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "metric" TEXT CHECK ("metric" IN ('negative_mention_count', 'mention_volume', 'average_rating', 'average_sentiment', 'unanswered_negative_count')) not null,
  "comparator" TEXT CHECK ("comparator" IN ('gte', 'lte')) not null,
  "threshold" REAL not null,
  "window_minutes" INTEGER not null default 1440,
  "minimum_sample_size" INTEGER not null default 1,
  "platforms" TEXT not null,
  "severity" TEXT CHECK ("severity" IN ('info', 'warning', 'critical')) not null default 'warning',
  "channels" TEXT not null,
  "cooldown_minutes" INTEGER not null default 360,
  "status" TEXT CHECK ("status" IN ('active', 'paused')) not null default 'active',
  "next_evaluation_at" TEXT,
  "last_evaluated_at" TEXT,
  "last_triggered_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alert_rules_team_name_unique" ON "reputation_alert_rules" ("team_id", "name");
CREATE INDEX IF NOT EXISTS "reputation_alert_rules_due_index" ON "reputation_alert_rules" ("status", "next_evaluation_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alert_rules_uuid_unique" ON "reputation_alert_rules" ("uuid");
