-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_field_values" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "value" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "custom_field_id" INTEGER REFERENCES "custom_fields"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "contact_field_values_unique" ON "contact_field_values" ("team_id", "contact_id", "custom_field_id");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_field_values_uuid_unique" ON "contact_field_values" ("uuid");
