-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_approvals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "action" TEXT not null,
  "payload" TEXT not null,
  "status" TEXT CHECK ("status" IN ('pending', 'approved', 'rejected', 'expired', 'cancelled')) not null default 'pending',
  "requested_by" INTEGER not null,
  "decided_by" INTEGER,
  "reason" TEXT,
  "expires_at" TEXT,
  "decided_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "automation_id" INTEGER REFERENCES "automations"("id"),
  "automation_run_id" INTEGER REFERENCES "automation_runs"("id"),
  "automation_step_run_id" INTEGER REFERENCES "automation_step_runs"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "automation_approvals_team_status_index" ON "automation_approvals" ("team_id", "status", "expires_at");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_approvals_uuid_unique" ON "automation_approvals" ("uuid");
