-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "email_messages" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "subject" TEXT not null,
  "preheader" TEXT,
  "from_name" TEXT not null,
  "from_address" TEXT not null,
  "reply_to" TEXT,
  "document" TEXT not null,
  "html" TEXT,
  "text" TEXT,
  "revision" INTEGER not null default 1,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_id" INTEGER REFERENCES "campaigns"("id"),
  "message_template_id" INTEGER REFERENCES "message_templates"("id"),
  "sender_identity_id" INTEGER REFERENCES "sender_identities"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "email_messages_team_campaign_index" ON "email_messages" ("team_id", "campaign_id");
CREATE UNIQUE INDEX IF NOT EXISTS "email_messages_uuid_unique" ON "email_messages" ("uuid");
