-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_tags" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "source" TEXT not null default 'manual',
  "applied_by" INTEGER,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "audience_tag_id" INTEGER REFERENCES "audience_tags"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "contact_tags_unique" ON "contact_tags" ("team_id", "contact_id", "audience_tag_id");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_tags_uuid_unique" ON "contact_tags" ("uuid");
