-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_memberships" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('active', 'pending', 'unsubscribed')) not null default 'active',
  "joined_at" TEXT not null,
  "left_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "audience_id" INTEGER REFERENCES "audiences"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "audience_memberships_unique" ON "audience_memberships" ("audience_id", "contact_id");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_memberships_uuid_unique" ON "audience_memberships" ("uuid");
