-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "ad_placements" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "slot_key" TEXT not null,
  "rate" INTEGER not null,
  "impressions" INTEGER not null default 0,
  "clicks" INTEGER not null default 0,
  "status" TEXT CHECK ("status" IN ('reserved', 'approved', 'delivered', 'cancelled')) not null default 'reserved',
  "team_id" INTEGER,
  "advertiser_offer_id" INTEGER REFERENCES "advertiser_offers"("id"),
  "campaign_id" INTEGER,
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "ad_placements_team_status" ON "ad_placements" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "ad_placements_offer_slot_unique" ON "ad_placements" ("advertiser_offer_id", "slot_key");
CREATE UNIQUE INDEX IF NOT EXISTS "ad_placements_uuid_unique" ON "ad_placements" ("uuid");
