-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "campaign_recipients" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms')) not null,
  "address_hash" TEXT not null,
  "status" TEXT CHECK ("status" IN ('queued', 'sent', 'delivered', 'failed', 'suppressed', 'cancelled')) not null default 'queued',
  "idempotency_key" TEXT not null,
  "snapshot" TEXT not null,
  "scheduled_at" TEXT,
  "team_id" INTEGER,
  "campaign_id" INTEGER,
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "campaign_variant_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_recipients_unique" ON "campaign_recipients" ("campaign_id", "contact_id");
CREATE INDEX IF NOT EXISTS "campaign_recipients_team_status" ON "campaign_recipients" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_recipients_uuid_unique" ON "campaign_recipients" ("uuid");
