-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "payouts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider_id" TEXT,
  "amount" INTEGER not null,
  "currency" TEXT not null default 'USD',
  "status" TEXT CHECK ("status" IN ('pending', 'processing', 'paid', 'failed', 'cancelled')) not null default 'pending',
  "scheduled_at" TEXT,
  "paid_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "payouts_team_status" ON "payouts" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "payouts_provider_id_unique" ON "payouts" ("provider_id");
CREATE UNIQUE INDEX IF NOT EXISTS "payouts_uuid_unique" ON "payouts" ("uuid");
