-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_step_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "node_id" TEXT not null,
  "type" TEXT not null,
  "status" TEXT CHECK ("status" IN ('queued', 'running', 'waiting', 'completed', 'failed', 'dead_lettered', 'cancelled')) not null default 'queued',
  "attempt" INTEGER not null default 1,
  "idempotency_key" TEXT not null,
  "input" TEXT,
  "output" TEXT,
  "error" TEXT,
  "available_at" TEXT,
  "started_at" TEXT,
  "completed_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "automation_run_id" INTEGER REFERENCES "automation_runs"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "automation_step_runs_idempotency_unique" ON "automation_step_runs" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_step_runs_uuid_unique" ON "automation_step_runs" ("uuid");
