-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_delivery_routes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "courier" TEXT not null,
  "vehicle" TEXT not null,
  "stops" INTEGER not null,
  "delivery_time" INTEGER not null,
  "total_distance" INTEGER not null,
  "last_active" TEXT not null,
  "status" TEXT CHECK ("status" IN ('planned', 'active', 'completed', 'cancelled')) default 'planned',
  "started_at" TEXT,
  "completed_at" TEXT,
  "courier_id" INTEGER REFERENCES "couriers"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_delivery_routes" ("id", "courier", "vehicle", "stops", "delivery_time", "total_distance", "last_active", "status", "started_at", "completed_at", "created_at", "updated_at", "uuid") SELECT "id", "driver", "vehicle", "stops", "delivery_time", "total_distance", "last_active", "status", "started_at", "completed_at", "created_at", "updated_at", "uuid" FROM "delivery_routes";
DROP TABLE "delivery_routes";
ALTER TABLE "_qb_tmp_delivery_routes" RENAME TO "delivery_routes";
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_routes_uuid_unique" ON "delivery_routes" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_categorizable_models" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "category_id" INTEGER not null REFERENCES "categorizables"("id"),
  "categorizable_id" INTEGER not null,
  "categorizable_type" TEXT not null default 'posts',
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
INSERT INTO "_qb_tmp_categorizable_models" ("id", "category_id", "categorizable_id", "categorizable_type", "created_at", "updated_at") SELECT "id", "category_id", "categorizable_id", "categorizable_type", "created_at", "updated_at" FROM "categorizable_models";
DROP TABLE "categorizable_models";
ALTER TABLE "_qb_tmp_categorizable_models" RENAME TO "categorizable_models";
CREATE UNIQUE INDEX IF NOT EXISTS "categorizable_models_category_id_categorizable_id_categ_166kkzm" ON "categorizable_models" ("category_id", "categorizable_id", "categorizable_type");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
