-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_submissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "payload" TEXT not null,
  "dedupe_key" TEXT not null,
  "source_url" TEXT,
  "ip_hash" TEXT,
  "status" TEXT CHECK ("status" IN ('accepted', 'confirmed', 'rejected', 'spam')) not null default 'accepted',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "form_definition_id" INTEGER REFERENCES "form_definitions"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "form_submissions_team_created" ON "form_submissions" ("team_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "form_submissions_dedupe_unique" ON "form_submissions" ("form_definition_id", "dedupe_key");
CREATE UNIQUE INDEX IF NOT EXISTS "form_submissions_uuid_unique" ON "form_submissions" ("uuid");
