-- qb:generated
-- @generated by `buddy migrate:regenerate` - edits will be overwritten
CREATE TABLE IF NOT EXISTS "oauth_access_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "tokenable_type" TEXT,
  "tokenable_id" INTEGER,
  "name" TEXT,
  "token" TEXT,
  "scopes" TEXT,
  "revoked" INTEGER default 0,
  "expires_at" TEXT,
  "user_agent" TEXT,
  "ip_address" TEXT,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT
);
