-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audiences" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "description" TEXT,
  "channel" TEXT CHECK ("channel" IN ('all', 'email', 'sms')) not null default 'all',
  "member_count" INTEGER not null default 0,
  "team_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "audiences_team_name_unique" ON "audiences" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "audiences_uuid_unique" ON "audiences" ("uuid");
