-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "webhook_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT not null,
  "provider_event_id" TEXT not null,
  "type" TEXT not null,
  "status" TEXT CHECK ("status" IN ('received', 'processing', 'processed', 'failed', 'dead_lettered')) not null default 'received',
  "payload" TEXT not null,
  "signature_verified" INTEGER not null default 0,
  "attempts" INTEGER not null default 0,
  "error" TEXT,
  "processed_at" TEXT,
  "team_id" INTEGER,
  "webhook_endpoint_id" INTEGER REFERENCES "webhook_endpoints"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_events_provider_unique" ON "webhook_events" ("provider", "provider_event_id");
CREATE UNIQUE INDEX IF NOT EXISTS "webhook_events_uuid_unique" ON "webhook_events" ("uuid");
