-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "custom_fields" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "key" TEXT not null,
  "type" TEXT CHECK ("type" IN ('text', 'number', 'boolean', 'date', 'select', 'json')) not null,
  "options" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "custom_fields_team_key_unique" ON "custom_fields" ("team_id", "key");
CREATE UNIQUE INDEX IF NOT EXISTS "custom_fields_uuid_unique" ON "custom_fields" ("uuid");
