-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "gated_resources" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "access" TEXT CHECK ("access" IN ('subscriber', 'paid', 'product', 'segment')) not null default 'subscriber',
  "segment_id" INTEGER,
  "storage_key" TEXT,
  "content" TEXT not null,
  "status" TEXT CHECK ("status" IN ('draft', 'published', 'archived')) not null default 'draft',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "product_id" INTEGER REFERENCES "products"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "gated_resources_team_slug_unique" ON "gated_resources" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "gated_resources_uuid_unique" ON "gated_resources" ("uuid");
