-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "data_requests" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT CHECK ("type" IN ('access', 'export', 'erasure', 'restriction', 'correction')) not null,
  "status" TEXT CHECK ("status" IN ('pending', 'verifying', 'processing', 'completed', 'rejected')) not null default 'pending',
  "jurisdiction" TEXT,
  "requested_at" TEXT not null,
  "completed_at" TEXT,
  "proof" TEXT,
  "team_id" INTEGER,
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "data_requests_team_status_index" ON "data_requests" ("team_id", "status", "requested_at");
CREATE UNIQUE INDEX IF NOT EXISTS "data_requests_uuid_unique" ON "data_requests" ("uuid");
