-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "attribution_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "kind" TEXT CHECK ("kind" IN ('visit', 'signup', 'conversion', 'purchase', 'renewal', 'churn')) not null,
  "source" TEXT not null,
  "medium" TEXT,
  "campaign_key" TEXT,
  "revenue" INTEGER,
  "currency" TEXT,
  "dedupe_key" TEXT not null,
  "occurred_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "commerce_event_id" INTEGER REFERENCES "commerce_events"("id"),
  "campaign_id" INTEGER REFERENCES "campaigns"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "attribution_events_team_occurred" ON "attribution_events" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "attribution_events_dedupe_unique" ON "attribution_events" ("team_id", "dedupe_key");
CREATE UNIQUE INDEX IF NOT EXISTS "attribution_events_uuid_unique" ON "attribution_events" ("uuid");
