-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_dead_letters" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "node_id" TEXT not null,
  "payload" TEXT not null,
  "error_class" TEXT not null,
  "error_message" TEXT not null,
  "attempts" INTEGER not null default 1,
  "status" TEXT CHECK ("status" IN ('open', 'replaying', 'recovered', 'discarded')) not null default 'open',
  "recovered_by" INTEGER,
  "recovered_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "automation_id" INTEGER REFERENCES "automations"("id"),
  "automation_run_id" INTEGER REFERENCES "automation_runs"("id"),
  "automation_step_run_id" INTEGER REFERENCES "automation_step_runs"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "automation_dead_letters_team_status_index" ON "automation_dead_letters" ("team_id", "status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_dead_letters_uuid_unique" ON "automation_dead_letters" ("uuid");
