-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sponsors" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "contact_email" TEXT not null,
  "website" TEXT,
  "status" TEXT CHECK ("status" IN ('prospect', 'active', 'paused', 'blocked')) not null default 'prospect',
  "notes" TEXT,
  "team_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "sponsors_team_name" ON "sponsors" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "sponsors_uuid_unique" ON "sponsors" ("uuid");
