-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "integration_credentials" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT CHECK ("provider" IN ('twilio', 'stripe', 'shopify', 'woocommerce', 'mail', 'bedrock', 'yelp', 'google_business', 'generic')) not null,
  "name" TEXT not null,
  "encrypted_value" TEXT not null,
  "last_four" TEXT,
  "rotated_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "integration_credentials_team_provider_unique" ON "integration_credentials" ("team_id", "provider", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "integration_credentials_uuid_unique" ON "integration_credentials" ("uuid");
