-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contact_merges" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "source_contact_uuid" TEXT not null,
  "snapshot" TEXT not null,
  "merged_by_user_id" INTEGER not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "contact_merges_team_created_index" ON "contact_merges" ("team_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "contact_merges_uuid_unique" ON "contact_merges" ("uuid");
