-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "sms_messages" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "body" TEXT not null,
  "encoding" TEXT CHECK ("encoding" IN ('gsm7', 'ucs2')) not null default 'gsm7',
  "segment_count" INTEGER not null default 1,
  "stop_language_included" INTEGER not null default 1,
  "quiet_hours_timezone" TEXT not null default 'recipient',
  "revision" INTEGER not null default 1,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_id" INTEGER REFERENCES "campaigns"("id"),
  "sender_identity_id" INTEGER REFERENCES "sender_identities"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "sms_messages_team_campaign_index" ON "sms_messages" ("team_id", "campaign_id");
CREATE UNIQUE INDEX IF NOT EXISTS "sms_messages_uuid_unique" ON "sms_messages" ("uuid");
