-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "segment_rules" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "field" TEXT not null,
  "operator" TEXT CHECK ("operator" IN ('equals', 'not_equals', 'contains', 'greater_than', 'less_than', 'before', 'after', 'exists', 'not_exists', 'in')) not null,
  "value" TEXT,
  "position" INTEGER not null default 0,
  "team_id" INTEGER,
  "segment_id" INTEGER REFERENCES "segments"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "segment_rules_segment_position_index" ON "segment_rules" ("segment_id", "position");
CREATE UNIQUE INDEX IF NOT EXISTS "segment_rules_uuid_unique" ON "segment_rules" ("uuid");
