-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commerce_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "external_id" TEXT not null,
  "type" TEXT CHECK ("type" IN ('product_viewed', 'cart_updated', 'checkout_started', 'order_created', 'order_paid', 'order_fulfilled', 'order_refunded', 'subscription_changed')) not null,
  "amount" INTEGER,
  "currency" TEXT default 'USD',
  "payload" TEXT not null,
  "occurred_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "commerce_connection_id" INTEGER REFERENCES "commerce_connections"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_events_provider_unique" ON "commerce_events" ("commerce_connection_id", "external_id");
CREATE INDEX IF NOT EXISTS "commerce_events_team_type_index" ON "commerce_events" ("team_id", "type", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_events_uuid_unique" ON "commerce_events" ("uuid");
