-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audit_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "action" TEXT not null,
  "subject_type" TEXT,
  "subject_id" TEXT,
  "metadata" TEXT not null,
  "ip_address" TEXT,
  "occurred_at" TEXT not null,
  "team_id" INTEGER,
  "user_id" INTEGER,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "audit_events_team_occurred_index" ON "audit_events" ("team_id", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "audit_events_uuid_unique" ON "audit_events" ("uuid");
