-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "podcasts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT not null,
  "slug" TEXT not null,
  "description" TEXT,
  "author" TEXT not null,
  "explicit" INTEGER not null default 0,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'archived')) not null default 'draft',
  "team_id" INTEGER,
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "podcasts_team_slug_unique" ON "podcasts" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "podcasts_uuid_unique" ON "podcasts" ("uuid");
