-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "landing_pages" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "status" TEXT CHECK ("status" IN ('draft', 'scheduled', 'published', 'archived')) not null default 'draft',
  "document" TEXT not null,
  "seo" TEXT not null,
  "published_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "site_id" INTEGER REFERENCES "sites"("id"),
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "landing_pages_team_slug_unique" ON "landing_pages" ("team_id", "site_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "landing_pages_uuid_unique" ON "landing_pages" ("uuid");
