-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "automation_versions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "version" INTEGER not null,
  "graph" TEXT not null,
  "checksum" TEXT not null,
  "published_by" INTEGER not null,
  "published_at" TEXT not null,
  "team_id" INTEGER,
  "automation_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "automation_versions_unique" ON "automation_versions" ("automation_id", "version");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_versions_uuid_unique" ON "automation_versions" ("uuid");
