-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "publication_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('pending', 'active', 'cancelled', 'past_due')) not null default 'pending',
  "tier" TEXT not null default 'free',
  "started_at" TEXT,
  "ended_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "publication_members_unique" ON "publication_members" ("publication_id", "contact_id");
CREATE INDEX IF NOT EXISTS "publication_members_team_status" ON "publication_members" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "publication_members_uuid_unique" ON "publication_members" ("uuid");
