-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "commerce_connections" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "provider" TEXT CHECK ("provider" IN ('stacks', 'shopify', 'woocommerce', 'stripe', 'csv', 'api')) not null,
  "name" TEXT not null,
  "external_account_id" TEXT,
  "encrypted_credentials" TEXT,
  "status" TEXT CHECK ("status" IN ('pending', 'active', 'error', 'disabled')) not null default 'pending',
  "cursor" TEXT,
  "last_synced_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_connections_team_provider_unique" ON "commerce_connections" ("team_id", "provider", "external_account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "commerce_connections_uuid_unique" ON "commerce_connections" ("uuid");
