-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_automation_step_runs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "node_id" TEXT not null,
  "type" TEXT not null,
  "status" TEXT CHECK ("status" IN ('queued', 'running', 'waiting', 'completed', 'failed', 'dead_lettered', 'cancelled')) not null default 'queued',
  "attempt" INTEGER not null default 1,
  "idempotency_key" TEXT not null,
  "input" TEXT,
  "output" TEXT,
  "error" TEXT,
  "available_at" TEXT,
  "started_at" TEXT,
  "completed_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "automation_run_id" INTEGER REFERENCES "automation_runs"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_automation_step_runs" ("id", "node_id", "type", "status", "attempt", "idempotency_key", "input", "output", "error", "available_at", "started_at", "completed_at", "team_id", "automation_run_id", "created_at", "updated_at", "uuid") SELECT "id", "node_id", "type", "status", "attempt", "idempotency_key", "input", "output", "error", "available_at", "started_at", "completed_at", "team_id", "automation_run_id", "created_at", "updated_at", "uuid" FROM "automation_step_runs";
DROP TABLE "automation_step_runs";
ALTER TABLE "_qb_tmp_automation_step_runs" RENAME TO "automation_step_runs";
CREATE UNIQUE INDEX IF NOT EXISTS "automation_step_runs_idempotency_unique" ON "automation_step_runs" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_step_runs_uuid_unique" ON "automation_step_runs" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_automation_versions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "version" INTEGER not null,
  "graph" TEXT not null,
  "checksum" TEXT not null,
  "published_by" INTEGER not null,
  "published_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "automation_id" INTEGER REFERENCES "automations"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_automation_versions" ("id", "version", "graph", "checksum", "published_by", "published_at", "team_id", "automation_id", "created_at", "updated_at", "uuid") SELECT "id", "version", "graph", "checksum", "published_by", "published_at", "team_id", "automation_id", "created_at", "updated_at", "uuid" FROM "automation_versions";
DROP TABLE "automation_versions";
ALTER TABLE "_qb_tmp_automation_versions" RENAME TO "automation_versions";
CREATE UNIQUE INDEX IF NOT EXISTS "automation_versions_unique" ON "automation_versions" ("automation_id", "version");
CREATE UNIQUE INDEX IF NOT EXISTS "automation_versions_uuid_unique" ON "automation_versions" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_campaign_recipients" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms')) not null,
  "address_hash" TEXT not null,
  "status" TEXT CHECK ("status" IN ('queued', 'sent', 'delivered', 'failed', 'suppressed', 'cancelled')) not null default 'queued',
  "idempotency_key" TEXT not null,
  "snapshot" TEXT not null,
  "scheduled_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_id" INTEGER REFERENCES "campaigns"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "campaign_variant_id" INTEGER REFERENCES "campaign_variants"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_campaign_recipients" ("id", "channel", "address_hash", "status", "idempotency_key", "snapshot", "scheduled_at", "team_id", "campaign_id", "contact_id", "campaign_variant_id", "created_at", "updated_at", "uuid") SELECT "id", "channel", "address_hash", "status", "idempotency_key", "snapshot", "scheduled_at", "team_id", "campaign_id", "contact_id", "campaign_variant_id", "created_at", "updated_at", "uuid" FROM "campaign_recipients";
DROP TABLE "campaign_recipients";
ALTER TABLE "_qb_tmp_campaign_recipients" RENAME TO "campaign_recipients";
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_recipients_unique" ON "campaign_recipients" ("campaign_id", "contact_id");
CREATE INDEX IF NOT EXISTS "campaign_recipients_team_status" ON "campaign_recipients" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_recipients_uuid_unique" ON "campaign_recipients" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_campaign_sends" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "campaign_id" INTEGER not null REFERENCES "campaigns"("id"),
  "subscriber_id" INTEGER REFERENCES "subscribers"("id"),
  "email_list_id" INTEGER REFERENCES "email_lists"("id"),
  "status" TEXT CHECK ("status" IN ('queued', 'deferred', 'sending', 'sent', 'delivered', 'failed', 'undelivered', 'bounced', 'complained', 'suppressed', 'cancelled')) not null default 'queued',
  "channel" TEXT CHECK ("channel" IN ('email', 'sms', 'push')) not null default 'email',
  "recipient" TEXT not null,
  "idempotency_key" TEXT not null,
  "provider_message_id" TEXT,
  "error" TEXT,
  "sent_at" TEXT,
  "opened_at" TEXT,
  "clicked_at" TEXT,
  "delivered_at" TEXT,
  "failed_at" TEXT,
  "segments" INTEGER,
  "cost" INTEGER,
  "metadata" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_variant_id" INTEGER REFERENCES "campaign_variants"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_campaign_sends" ("id", "campaign_id", "subscriber_id", "email_list_id", "status", "provider_message_id", "error", "sent_at", "opened_at", "clicked_at", "created_at", "updated_at", "uuid") SELECT "id", "campaign_id", "subscriber_id", "email_list_id", "status", "provider_message_id", "error", "sent_at", "opened_at", "clicked_at", "created_at", "updated_at", "uuid" FROM "campaign_sends";
DROP TABLE "campaign_sends";
ALTER TABLE "_qb_tmp_campaign_sends" RENAME TO "campaign_sends";
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_sends_idempotency_unique" ON "campaign_sends" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "campaign_sends_uuid_unique" ON "campaign_sends" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_form_definitions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "kind" TEXT CHECK ("kind" IN ('inline', 'popup', 'landing_page', 'gated_resource')) not null default 'inline',
  "schema_document" TEXT not null,
  "double_opt_in" INTEGER not null default 1,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'archived')) not null default 'draft',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "site_id" INTEGER REFERENCES "sites"("id"),
  "audience_id" INTEGER REFERENCES "audiences"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_form_definitions" ("id", "name", "slug", "kind", "schema_document", "double_opt_in", "status", "team_id", "site_id", "audience_id", "created_at", "updated_at", "uuid") SELECT "id", "name", "slug", "kind", "schema_document", "double_opt_in", "status", "team_id", "site_id", "audience_id", "created_at", "updated_at", "uuid" FROM "form_definitions";
DROP TABLE "form_definitions";
ALTER TABLE "_qb_tmp_form_definitions" RENAME TO "form_definitions";
CREATE UNIQUE INDEX IF NOT EXISTS "form_definitions_team_slug_unique" ON "form_definitions" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "form_definitions_uuid_unique" ON "form_definitions" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_publications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "description" TEXT,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'paused', 'archived')) not null default 'draft',
  "access" TEXT CHECK ("access" IN ('free', 'paid', 'mixed')) not null default 'free',
  "settings" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "site_id" INTEGER REFERENCES "sites"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_publications" ("id", "name", "slug", "description", "status", "access", "settings", "team_id", "site_id", "created_at", "updated_at", "uuid") SELECT "id", "name", "slug", "description", "status", "access", "settings", "team_id", "site_id", "created_at", "updated_at", "uuid" FROM "publications";
DROP TABLE "publications";
ALTER TABLE "_qb_tmp_publications" RENAME TO "publications";
CREATE UNIQUE INDEX IF NOT EXISTS "publications_team_slug_unique" ON "publications" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "publications_uuid_unique" ON "publications" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_sender_identities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms')) not null,
  "name" TEXT not null,
  "address" TEXT not null,
  "reply_to" TEXT,
  "status" TEXT CHECK ("status" IN ('pending', 'verified', 'disabled', 'failed')) not null default 'pending',
  "verification" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "sender_domain_id" INTEGER REFERENCES "sender_domains"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_sender_identities" ("id", "channel", "name", "address", "reply_to", "status", "verification", "team_id", "sender_domain_id", "created_at", "updated_at", "uuid") SELECT "id", "channel", "name", "address", "reply_to", "status", "verification", "team_id", "sender_domain_id", "created_at", "updated_at", "uuid" FROM "sender_identities";
DROP TABLE "sender_identities";
ALTER TABLE "_qb_tmp_sender_identities" RENAME TO "sender_identities";
CREATE UNIQUE INDEX IF NOT EXISTS "sender_identities_team_address_unique" ON "sender_identities" ("team_id", "channel", "address");
CREATE UNIQUE INDEX IF NOT EXISTS "sender_identities_uuid_unique" ON "sender_identities" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
