-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "entitlements" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "key" TEXT not null,
  "value" TEXT not null,
  "source" TEXT CHECK ("source" IN ('plan', 'override', 'promotion')) not null default 'plan',
  "expires_at" TEXT,
  "team_id" INTEGER,
  "subscription_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "entitlements_team_key_unique" ON "entitlements" ("team_id", "key");
CREATE UNIQUE INDEX IF NOT EXISTS "entitlements_uuid_unique" ON "entitlements" ("uuid");
