-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "advertiser_offers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "creative" TEXT not null,
  "budget" INTEGER not null,
  "currency" TEXT not null default 'USD',
  "starts_at" TEXT,
  "ends_at" TEXT,
  "status" TEXT CHECK ("status" IN ('draft', 'offered', 'accepted', 'active', 'completed', 'cancelled')) not null default 'draft',
  "team_id" INTEGER,
  "sponsor_id" INTEGER REFERENCES "sponsors"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "advertiser_offers_team_status" ON "advertiser_offers" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "advertiser_offers_uuid_unique" ON "advertiser_offers" ("uuid");
