-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "segments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "description" TEXT,
  "match_type" TEXT CHECK ("match_type" IN ('all', 'any')) not null default 'all',
  "estimated_count" INTEGER not null default 0,
  "refreshed_at" TEXT,
  "team_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "segments_team_name_unique" ON "segments" ("team_id", "name");
CREATE UNIQUE INDEX IF NOT EXISTS "segments_uuid_unique" ON "segments" ("uuid");
