-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "monitored_profiles" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "platform" TEXT CHECK ("platform" IN ('google_business', 'yelp', 'facebook', 'instagram', 'x', 'tiktok', 'linkedin', 'youtube', 'trustpilot', 'reddit')) not null,
  "kind" TEXT CHECK ("kind" IN ('business_listing', 'social_handle')) not null,
  "display_name" TEXT not null,
  "handle" TEXT,
  "external_id" TEXT not null,
  "location_label" TEXT,
  "profile_url" TEXT,
  "status" TEXT CHECK ("status" IN ('active', 'paused', 'unconfigured', 'error')) not null default 'unconfigured',
  "poll_interval_minutes" INTEGER not null default 30,
  "next_poll_at" TEXT,
  "last_polled_at" TEXT,
  "last_mention_at" TEXT,
  "cursor" TEXT,
  "consecutive_failures" INTEGER not null default 0,
  "last_error" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "integration_credential_id" INTEGER REFERENCES "integration_credentials"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "monitored_profiles_team_platform_external_unique" ON "monitored_profiles" ("team_id", "platform", "external_id");
CREATE INDEX IF NOT EXISTS "monitored_profiles_due_index" ON "monitored_profiles" ("status", "next_poll_at");
CREATE UNIQUE INDEX IF NOT EXISTS "monitored_profiles_uuid_unique" ON "monitored_profiles" ("uuid");
