-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "data_retention_policies" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "kind" TEXT CHECK ("kind" IN ('contacts', 'events', 'deliveries', 'analytics', 'audit', 'integrations')) not null,
  "retention_days" INTEGER not null,
  "legal_hold" INTEGER not null default 0,
  "jurisdiction" TEXT,
  "status" TEXT CHECK ("status" IN ('active', 'paused')) not null default 'active',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "data_retention_policies_team_kind_unique" ON "data_retention_policies" ("team_id", "kind");
CREATE UNIQUE INDEX IF NOT EXISTS "data_retention_policies_uuid_unique" ON "data_retention_policies" ("uuid");
