-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "form_definitions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT not null,
  "slug" TEXT not null,
  "kind" TEXT CHECK ("kind" IN ('inline', 'popup', 'landing_page', 'gated_resource')) not null default 'inline',
  "schema_document" TEXT not null,
  "double_opt_in" INTEGER not null default 1,
  "status" TEXT CHECK ("status" IN ('draft', 'active', 'archived')) not null default 'draft',
  "team_id" INTEGER REFERENCES "teams"("id"),
  "site_id" INTEGER REFERENCES "sites"("id"),
  "audience_id" INTEGER REFERENCES "audiences"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "form_definitions_team_slug_unique" ON "form_definitions" ("team_id", "slug");
CREATE UNIQUE INDEX IF NOT EXISTS "form_definitions_uuid_unique" ON "form_definitions" ("uuid");
