-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "contacts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "email" TEXT,
  "phone" TEXT,
  "first_name" TEXT,
  "last_name" TEXT,
  "status" TEXT CHECK ("status" IN ('active', 'pending', 'unsubscribed', 'suppressed', 'archived')) not null default 'active',
  "source" TEXT not null default 'manual',
  "properties" TEXT,
  "last_engaged_at" TEXT,
  "team_id" INTEGER,
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "contacts_team_email_unique" ON "contacts" ("team_id", "email");
CREATE INDEX IF NOT EXISTS "contacts_team_status_index" ON "contacts" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "contacts_uuid_unique" ON "contacts" ("uuid");
