-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "referrals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT not null,
  "referred_email_hash" TEXT not null,
  "status" TEXT CHECK ("status" IN ('clicked', 'pending', 'qualified', 'rewarded', 'rejected')) not null default 'clicked',
  "reward" TEXT,
  "qualified_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "publication_id" INTEGER REFERENCES "publications"("id"),
  "contact_id" INTEGER REFERENCES "contacts"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "referrals_team_code_unique" ON "referrals" ("team_id", "code");
CREATE INDEX IF NOT EXISTS "referrals_team_status" ON "referrals" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "referrals_uuid_unique" ON "referrals" ("uuid");
