-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "usage_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "meter" TEXT not null,
  "quantity" INTEGER not null,
  "source_type" TEXT not null,
  "source_id" TEXT,
  "idempotency_key" TEXT not null,
  "provider_cost" INTEGER not null default 0,
  "metadata" TEXT not null,
  "occurred_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_team_key_unique" ON "usage_events" ("team_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "usage_events_team_meter_index" ON "usage_events" ("team_id", "meter", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_uuid_unique" ON "usage_events" ("uuid");
