-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "reputation_alerts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "fingerprint" TEXT not null,
  "metric" TEXT CHECK ("metric" IN ('negative_mention_count', 'mention_volume', 'average_rating', 'average_sentiment', 'unanswered_negative_count')) not null,
  "severity" TEXT CHECK ("severity" IN ('info', 'warning', 'critical')) not null default 'warning',
  "observed_value" REAL not null,
  "threshold_value" REAL not null,
  "sample_size" INTEGER not null default 0,
  "window_start" TEXT not null,
  "window_end" TEXT not null,
  "status" TEXT CHECK ("status" IN ('open', 'acknowledged', 'resolved')) not null default 'open',
  "context" TEXT not null,
  "notified_channels" TEXT not null,
  "acknowledged_by" INTEGER,
  "acknowledged_at" TEXT,
  "resolved_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "reputation_alert_rule_id" INTEGER REFERENCES "reputation_alert_rules"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alerts_team_fingerprint_unique" ON "reputation_alerts" ("team_id", "fingerprint");
CREATE INDEX IF NOT EXISTS "reputation_alerts_team_status_index" ON "reputation_alerts" ("team_id", "status", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "reputation_alerts_uuid_unique" ON "reputation_alerts" ("uuid");
