-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "delivery_attempts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "channel" TEXT CHECK ("channel" IN ('email', 'sms')) not null,
  "provider" TEXT not null,
  "provider_message_id" TEXT,
  "idempotency_key" TEXT not null,
  "attempt" INTEGER not null default 1,
  "status" TEXT CHECK ("status" IN ('pending', 'sending', 'deferred', 'sent', 'failed', 'dead_lettered')) not null default 'pending',
  "retry_class" TEXT CHECK ("retry_class" IN ('transient', 'rate_limited', 'permanent', 'suppressed')),
  "error_code" TEXT,
  "error_message" TEXT,
  "retry_at" TEXT,
  "attempted_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "campaign_recipient_id" INTEGER REFERENCES "campaign_recipients"("id"),
  "campaign_send_id" INTEGER REFERENCES "campaign_sends"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_attempts_idempotency_unique" ON "delivery_attempts" ("team_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "delivery_attempts_status_retry_index" ON "delivery_attempts" ("team_id", "status", "retry_at");
CREATE UNIQUE INDEX IF NOT EXISTS "delivery_attempts_uuid_unique" ON "delivery_attempts" ("uuid");
