-- @generated by `buddy migrate:regenerate` — edits will be overwritten
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_subscriptions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT not null,
  "plan" TEXT not null,
  "provider_id" TEXT not null,
  "provider_status" TEXT not null,
  "unit_price" INTEGER not null default 0,
  "provider_type" TEXT not null,
  "provider_price_id" TEXT,
  "provider_customer_id" TEXT,
  "quantity" INTEGER not null default 1,
  "cancel_at_period_end" INTEGER not null default 0,
  "trial_ends_at" TEXT,
  "ends_at" TEXT,
  "last_used_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_subscriptions" ("id", "type", "plan", "provider_id", "provider_status", "unit_price", "provider_type", "provider_price_id", "quantity", "trial_ends_at", "ends_at", "last_used_at", "user_id", "uuid") SELECT "id", "type", "plan", "provider_id", "provider_status", "unit_price", "provider_type", "provider_price_id", "quantity", "trial_ends_at", "ends_at", "last_used_at", "user_id", "uuid" FROM "subscriptions";
DROP TABLE "subscriptions";
ALTER TABLE "_qb_tmp_subscriptions" RENAME TO "subscriptions";
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptions_provider_id_unique" ON "subscriptions" ("provider_id");
CREATE INDEX IF NOT EXISTS "subscriptions_team_status_index" ON "subscriptions" ("team_id", "provider_status");
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptions_uuid_unique" ON "subscriptions" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_usage_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "meter" TEXT not null,
  "quantity" INTEGER not null,
  "source_type" TEXT not null,
  "source_id" TEXT,
  "idempotency_key" TEXT not null,
  "provider_cost" INTEGER not null default 0,
  "metadata" TEXT not null,
  "occurred_at" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "user_id" INTEGER REFERENCES "users"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_usage_events" ("id", "meter", "quantity", "idempotency_key", "metadata", "occurred_at", "team_id", "created_at", "updated_at", "uuid") SELECT "id", "meter", "quantity", "idempotency_key", "metadata", "occurred_at", "team_id", "created_at", "updated_at", "uuid" FROM "usage_events";
DROP TABLE "usage_events";
ALTER TABLE "_qb_tmp_usage_events" RENAME TO "usage_events";
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_team_key_unique" ON "usage_events" ("team_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "usage_events_team_meter_index" ON "usage_events" ("team_id", "meter", "occurred_at");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_events_uuid_unique" ON "usage_events" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE "_qb_tmp_usage_meters" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "key" TEXT CHECK ("key" IN ('contacts', 'emails', 'sms_segments', 'ai_generations', 'custom_domains')) not null,
  "quantity" INTEGER not null default 0,
  "included_quantity" INTEGER,
  "period_start" TEXT not null,
  "period_end" TEXT not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
INSERT INTO "_qb_tmp_usage_meters" ("id", "key", "quantity", "included_quantity", "period_start", "period_end", "team_id", "created_at", "updated_at", "uuid") SELECT "id", "key", "quantity", "included_quantity", "period_start", "period_end", "team_id", "created_at", "updated_at", "uuid" FROM "usage_meters";
DROP TABLE "usage_meters";
ALTER TABLE "_qb_tmp_usage_meters" RENAME TO "usage_meters";
CREATE UNIQUE INDEX IF NOT EXISTS "usage_meters_team_period_unique" ON "usage_meters" ("team_id", "key", "period_start");
CREATE UNIQUE INDEX IF NOT EXISTS "usage_meters_uuid_unique" ON "usage_meters" ("uuid");
PRAGMA foreign_key_check;
COMMIT;
PRAGMA foreign_keys=ON;
