-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "audience_exports" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "status" TEXT CHECK ("status" IN ('pending', 'processing', 'completed', 'expired', 'failed')) not null default 'pending',
  "filters" TEXT not null,
  "storage_key" TEXT,
  "row_count" INTEGER not null default 0,
  "expires_at" TEXT,
  "completed_at" TEXT,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "audience_id" INTEGER REFERENCES "audiences"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "audience_exports_team_status_index" ON "audience_exports" ("team_id", "status");
CREATE UNIQUE INDEX IF NOT EXISTS "audience_exports_uuid_unique" ON "audience_exports" ("uuid");
