-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "segment_snapshots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "rule_checksum" TEXT not null,
  "contact_ids" TEXT not null,
  "contact_count" INTEGER not null default 0,
  "source" TEXT CHECK ("source" IN ('campaign', 'automation', 'export', 'preview')) not null default 'campaign',
  "created_by" INTEGER not null,
  "team_id" INTEGER REFERENCES "teams"("id"),
  "segment_id" INTEGER REFERENCES "segments"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE INDEX IF NOT EXISTS "segment_snapshots_team_segment_index" ON "segment_snapshots" ("team_id", "segment_id", "created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "segment_snapshots_uuid_unique" ON "segment_snapshots" ("uuid");
