import { describe, expect, it } from 'bun:test'
import { basename } from 'node:path'

async function files(pattern: string, cwd = import.meta.dir): Promise<string[]> {
  return Array.fromAsync(new Bun.Glob(pattern).scan({ cwd, absolute: true, onlyFiles: true }))
}

describe('tenant model contracts', () => {
  it('scopes every application model and generated API to Team', async () => {
    const modelFiles = await files('../../app/Models/*.ts')
    expect(modelFiles.length).toBeGreaterThanOrEqual(59)

    for (const file of modelFiles) {
      const source = await Bun.file(file).text()
      expect(source, `${basename(file)} must belong to Team`).toMatch(/belongsTo:\s*\[[^\]]*['"]Team['"]/s)
      expect(source, `${basename(file)} must protect API routes`).toContain("middleware: ['auth', 'team']")
    }
  })

  it('keeps schema changes model-generated', async () => {
    const sqliteMigrations = await files('../../database/migrations/*.sql')
    const postgresMigrations = await files('../../database/migrations/postgres/*.sql')
    const sqliteSnapshot = Bun.file(new URL('../../storage/framework/database/model-snapshot.sqlite.json', import.meta.url))
    const postgresSnapshot = Bun.file(new URL('../../storage/framework/database/model-snapshot.postgres.json', import.meta.url))

    expect(sqliteMigrations.length).toBeGreaterThan(250)
    expect(postgresMigrations.length).toBeGreaterThan(150)
    expect(await sqliteSnapshot.exists()).toBe(true)
    expect(await postgresSnapshot.exists()).toBe(true)

    for (const migration of postgresMigrations) {
      const source = await Bun.file(migration).text()
      expect(source, `${basename(migration)} must remain generator-owned`).toMatch(/^-- @generated by `buddy migrate:regenerate`/)
    }
  })
})

describe('interface contracts', () => {
  it('publishes a dedicated story for every feature in the navigation', async () => {
    const features = ['email', 'sms', 'publishing', 'forms', 'audience', 'automation', 'ai', 'deliverability', 'commerce', 'monetization', 'analytics', 'integrations']
    const navigation = await Bun.file(new URL('../../resources/components/CommsHQ/MarketingNavigation.stx', import.meta.url)).text()
    const stories = await Bun.file(new URL('../../resources/components/CommsHQ/FeatureStory.stx', import.meta.url)).text()

    expect(navigation).toContain('<details class="feature-menu group relative">')
    expect(navigation).toContain('aria-label="Primary navigation"')
    expect(navigation).toContain('Explore the complete platform')

    for (const feature of features) {
      const page = await Bun.file(new URL(`../../resources/views/${feature}.stx`, import.meta.url)).text()
      expect(navigation, `${feature} must be linked from the feature menu`).toContain(`href: '/${feature}'`)
      expect(stories, `${feature} must have a substantive feature story`).toContain(`  ${feature}: {`)
      expect(page, `${feature} must render its dedicated story`).toContain(`<FeatureStory feature="${feature}" />`)
    }
  })

  it('ships every primary product page through the shared state-rich surface', async () => {
    const required = ['onboarding', 'segments', 'editor', 'sites', 'forms', 'publications', 'commerce', 'monetization', 'analytics', 'integrations', 'billing', 'domains', 'senders', 'teams', 'settings']
    for (const page of required) {
      const source = await Bun.file(new URL(`../../resources/views/dashboard/commshq/${page}.stx`, import.meta.url)).text()
      expect(source).toContain(`<WorkspaceSurface area="${page}" />`)
    }

    const surface = await Bun.file(new URL('../../resources/components/CommsHQ/WorkspaceSurface.stx', import.meta.url)).text()
    for (const state of ['populated', 'loading', 'empty', 'error']) expect(surface).toContain(`'${state}'`)
  })

  it('publishes a footer-linked comparison page for every competitor', async () => {
    const competitors = ['mailchimp', 'klaviyo', 'kit', 'beehiiv', 'substack', 'birdeye', 'podium', 'hubspot', 'activecampaign', 'brevo', 'customer-io']
    const layout = await Bun.file(new URL('../../resources/views/layouts/marketing.stx', import.meta.url)).text()
    const comparisons = await Bun.file(new URL('../../resources/components/CommsHQ/CompetitorComparison.stx', import.meta.url)).text()
    const index = await Bun.file(new URL('../../resources/views/compare.stx', import.meta.url)).text()

    expect(layout, 'the footer must carry a Compare section').toContain('>Compare<')
    expect(layout).toContain('href="/compare"')

    for (const competitor of competitors) {
      const page = await Bun.file(new URL(`../../resources/views/compare/${competitor}.stx`, import.meta.url)).text()
      expect(page).toContain(`<CompetitorComparison competitor="${competitor}" />`)
      expect(page).toContain("@extends('layouts/marketing')")
      expect(layout, `${competitor} must be reachable from the footer`).toContain(`href="/compare/${competitor}"`)
      expect(index, `${competitor} must be listed on the compare index`).toContain(`href: '/compare/${competitor}'`)
      expect(comparisons, `${competitor} must have comparison content`).toContain(`  ${competitor.includes('-') ? `'${competitor}'` : competitor}: {`)
    }
  })

  it('keeps every comparison fair and checkable', async () => {
    const source = await Bun.file(new URL('../../resources/components/CommsHQ/CompetitorComparison.stx', import.meta.url)).text()
    // Each entry concedes strengths, says when to pick the other product, and
    // links out so a reader can verify the claims for themselves.
    expect(source.match(/strengths: \[/g) ?? []).toHaveLength(11)
    expect(source.match(/chooseRival: '/g) ?? []).toHaveLength(11)
    expect(source.match(/verify: 'https:\/\//g) ?? []).toHaveLength(11)
    expect(source).toContain('Reviewed {{ REVIEWED }}')
  })

  it('ships the public consent completion destinations', async () => {
    for (const page of ['subscription-confirmed', 'preferences-saved']) {
      const source = await Bun.file(new URL(`../../resources/views/${page}.stx`, import.meta.url)).text()
      expect(source).toContain("@extends('layouts/marketing')")
      expect(source).toContain('focus-visible:outline')
    }
  })

  it('rejects browser scripting, hand-drawn icons, and forbidden punctuation in product STX', async () => {
    const resourceFiles = await files('../../resources/**/*.stx')
    for (const file of resourceFiles) {
      const source = await Bun.file(file).text()
      expect(source, `${basename(file)} contains forbidden punctuation`).not.toMatch(/[—–]/)
      expect(source, `${basename(file)} contains direct browser scripting`).not.toMatch(/\b(?:window|document)\s*\./)
      expect(source, `${basename(file)} contains a hand-drawn SVG`).not.toMatch(/<svg\b/i)
    }
  })
})
